% This LilyPond file was generated by Rosegarden 1.6.1
\version "2.12.0"
% point and click debugging is disabled
#(ly:set-option 'point-and-click #f)
\header {
    copyright = "Unknown"
    subtitle = "blank"
    title = "Untitled"
    tagline = "Created using Rosegarden 1.6.1 and LilyPond"
}
#(set-global-staff-size 13)
#(set-default-paper-size "a4" 'landscape)
global = { 
    \time 4/4
    \skip 1*84  %% 1-84
}
globalTempo = {
    \override Score.MetronomeMark #'transparent = ##t
    \tempo 4 = 120  \skip 1*83 \skip 2 \skip 8 \skip 16 \skip 64 
}
\score {
    <<
        % force offset of colliding notes in chords:
        \override Score.NoteColumn #'force-hshift = #1.0

        \context Staff = "track 1" << 
            \set Staff.instrumentName = \markup { \column { "rhodes " } }
            \set Staff.midiInstrument = ""
            \set Score.skipBars = ##t
            \set Staff.printKeyCancellation = ##f
            \new Voice \global
            \new Voice \globalTempo

            \context Voice = "voice 1" {
                \override Voice.TextScript #'padding = #2.0
                \override MultiMeasureRest #'expand-limit = 1

                \skip 1*4 
%% 5
                \clef "alto"
                \key bes \major
                < f bes d' > 1  |
                < aes d' f > 1  |
                < a c' e > 2. r4  |
                < g bes ees > 1  |
                R1  |
%% 10
                < f d' bes > 1 
                % warning: overlong bar truncated here |
                R1  |
                < d' a f > 1 
                % warning: overlong bar truncated here |
                R1  |
                < bes d' f > 1 -\tenuto 
                % warning: overlong bar truncated here |
%% 15
                R1  |
                < a d' f > 1 -\tenuto 
                % warning: overlong bar truncated here |
                r2 r4 r4  |
                < f d' bes > 1 
                % warning: overlong bar truncated here |
                R1  |
%% 20
                < d' a f > 1 
                % warning: overlong bar truncated here |
                R1  |
                < bes d' f > 1 -\tenuto 
                % warning: overlong bar truncated here |
                R1  |
                < a d' f > 1 -\tenuto 
                % warning: overlong bar truncated here |
%% 25
                r2 r4 r4  |
                < f d' bes > 1 
                % warning: overlong bar truncated here |
                R1  |
                < d' a f > 1 
                % warning: overlong bar truncated here |
                R1  |
%% 30
                < bes d' f > 1 -\tenuto 
                % warning: overlong bar truncated here |
                R1  |
                < a d' f > 1 -\tenuto 
                % warning: overlong bar truncated here |
                r2 r4 r4  |
                < f d' bes > 1 
                % warning: overlong bar truncated here |
%% 35
                R1  |
                < d' a f > 1 
                % warning: overlong bar truncated here |
                R1  |
                < bes d' f > 1 -\tenuto 
                % warning: overlong bar truncated here |
                R1  |
%% 40
                < a d' f > 1 -\tenuto 
                % warning: overlong bar truncated here |
                r2 r4 r4  |
                < bes f d' > 1  |
                < d' aes f > 1  |
                < a c' e > 2. r4  |
%% 45
                < bes g ees > 1  |
                < bes d' f > 1 -\tenuto 
                % warning: overlong bar truncated here |
                r2 r4 r4  |
                < d' a f > 1 -\tenuto 
                % warning: overlong bar truncated here |
                R1  |
%% 50
                < bes d' f > 1 -\tenuto 
                % warning: overlong bar truncated here |
                r2 r2  |
                < d' a f > 1 -\tenuto 
                % warning: overlong bar truncated here |
                R1  |
                < bes d' f > 1 -\tenuto 
                % warning: overlong bar truncated here |
%% 55
                r2 r4 r4  |
                < d' a f > 1 -\tenuto 
                % warning: overlong bar truncated here |
                R1  |
                < bes d' f > 1 -\tenuto 
                % warning: overlong bar truncated here |
                r2 r2  |
%% 60
                < d' a f > 1 -\tenuto 
                % warning: overlong bar truncated here |
                R1  |
                < bes d' f > 1 -\tenuto 
                % warning: overlong bar truncated here |
                r2 r4 r4  |
                < d' a f > 1 -\tenuto 
                % warning: overlong bar truncated here |
%% 65
                R1  |
                < bes d' f > 1 -\tenuto 
                % warning: overlong bar truncated here |
                r2 r2  |
                < d' a f > 1 -\tenuto 
                % warning: overlong bar truncated here |
                R1  |
%% 70
                R1*7  |
                < bes d' f > 1 -\tenuto 
                % warning: overlong bar truncated here |
                r2 r4 r4  |
                < aes d' f > 1 -\tenuto 
                % warning: overlong bar truncated here |
%% 80
                r2 r2  |
                R1*2  |
                R1  |
                < g bes ees > 1 -\tenuto 
                % warning: overlong bar truncated here |
                r2 r8 r16 r64 
                % warning: bar too short, padding with rests
                % 45/64 < 4/4
                r64 r32 r4  |
                \bar "|."
            } % Voice
        >> % Staff

        \context Staff = "track 2" << 
            \set Staff.instrumentName = \markup { \column { "bajo " } }
            \set Staff.midiInstrument = ""
            \set Score.skipBars = ##t
            \set Staff.printKeyCancellation = ##f
            \new Voice \global
            \new Voice \globalTempo

            \context Voice = "voice 2" {
                \override Voice.TextScript #'padding = #2.0
                \override MultiMeasureRest #'expand-limit = 1

                \time 4/4
                \clef "bass"
                \key bes \major
                R1*4  |
%% 5
                bes, 1  |
                d 1 -\tenuto  |
                c 1 -\tenuto  |
                bes, 1  |
                R1  |
%% 10
                bes, 1 -\tenuto 
                % warning: overlong bar truncated here |
                R1  |
                d 1 -\tenuto 
                % warning: overlong bar truncated here |
                R1  |
                bes, 1 -\tenuto 
                % warning: overlong bar truncated here |
%% 15
                R1  |
                f 1 -\tenuto 
                % warning: overlong bar truncated here |
                r2 r2  |
                bes, 1 -\tenuto 
                % warning: overlong bar truncated here |
                R1  |
%% 20
                d 1 -\tenuto 
                % warning: overlong bar truncated here |
                R1  |
                bes, 1 -\tenuto 
                % warning: overlong bar truncated here |
                R1  |
                f 1 -\tenuto 
                % warning: overlong bar truncated here |
%% 25
                r2 r2  |
                bes, 1 -\tenuto 
                % warning: overlong bar truncated here |
                R1  |
                d 1 -\tenuto 
                % warning: overlong bar truncated here |
                R1  |
%% 30
                bes, 1 -\tenuto 
                % warning: overlong bar truncated here |
                R1  |
                f 1 -\tenuto 
                % warning: overlong bar truncated here |
                r2 r2  |
                bes, 1 -\tenuto 
                % warning: overlong bar truncated here |
%% 35
                R1  |
                d 1 -\tenuto 
                % warning: overlong bar truncated here |
                R1  |
                bes, 1 -\tenuto 
                % warning: overlong bar truncated here |
                R1  |
%% 40
                f 1 -\tenuto 
                % warning: overlong bar truncated here |
                r2 r2  |
                r2 r  |
                r2 r  |
                r2 r  |
%% 45
                r2 r  |
                bes, 1 -\tenuto 
                % warning: overlong bar truncated here |
                R1  |
                d 1 -\tenuto 
                % warning: overlong bar truncated here |
                R1  |
%% 50
                bes, 1 -\tenuto 
                % warning: overlong bar truncated here |
                R1  |
                f 1 -\tenuto 
                % warning: overlong bar truncated here |
                r2 r2  |
                bes, 1 -\tenuto 
                % warning: overlong bar truncated here |
%% 55
                R1  |
                d 1 -\tenuto 
                % warning: overlong bar truncated here |
                R1  |
                bes, 1 -\tenuto 
                % warning: overlong bar truncated here |
                R1  |
%% 60
                f 1 -\tenuto 
                % warning: overlong bar truncated here |
                r2 r2  |
                bes, 1 -\tenuto 
                % warning: overlong bar truncated here |
                R1  |
                d 1 -\tenuto 
                % warning: overlong bar truncated here |
%% 65
                R1  |
                bes, 1 -\tenuto 
                % warning: overlong bar truncated here |
                R1  |
                f 1 -\tenuto 
                % warning: overlong bar truncated here |
            } % Voice
        >> % Staff

        \context Staff = "track 3" << 
            \set Staff.instrumentName = \markup { \column { "pad " } }
            \set Staff.midiInstrument = ""
            \set Score.skipBars = ##t
            \set Staff.printKeyCancellation = ##f
            \new Voice \global
            \new Voice \globalTempo

            \context Voice = "voice 3" {
                \override Voice.TextScript #'padding = #2.0
                \override MultiMeasureRest #'expand-limit = 1

                \time 4/4
                \clef "alto"
                \key bes \major
                R1*9  |
%% 10
                < f d' bes > 1 
                % warning: overlong bar truncated here |
                R1  |
                < d' a f > 1 
                % warning: overlong bar truncated here |
                R1  |
                < bes d' f > 1 -\tenuto 
                % warning: overlong bar truncated here |
%% 15
                R1  |
                < a d' f > 1 -\tenuto 
                % warning: overlong bar truncated here |
                r2 r4 r4  |
                < f d' bes > 1 
                % warning: overlong bar truncated here |
                R1  |
%% 20
                < d' a f > 1 
                % warning: overlong bar truncated here |
                R1  |
                < bes d' f > 1 -\tenuto 
                % warning: overlong bar truncated here |
                R1  |
                < a d' f > 1 -\tenuto 
                % warning: overlong bar truncated here |
%% 25
                r2 r4 r4  |
                < f d' bes > 1 
                % warning: overlong bar truncated here |
                R1  |
                < d' a f > 1 
                % warning: overlong bar truncated here |
                R1  |
%% 30
                < bes d' f > 1 -\tenuto 
                % warning: overlong bar truncated here |
                R1  |
                < a d' f > 1 -\tenuto 
                % warning: overlong bar truncated here |
                r2 r4 r4  |
                < f d' bes > 1 
                % warning: overlong bar truncated here |
%% 35
                R1  |
                < d' a f > 1 
                % warning: overlong bar truncated here |
                R1  |
                < bes d' f > 1 -\tenuto 
                % warning: overlong bar truncated here |
                R1  |
%% 40
                < a d' f > 1 -\tenuto 
                % warning: overlong bar truncated here |
                r2 r4 r4  |
                < bes f d' > 1  |
                < d' aes f > 1  |
                < a c' e > 2. r4  |
%% 45
                < bes g ees > 1  |
                < bes d' f > 1 -\tenuto 
                % warning: overlong bar truncated here |
                r2 r4 r4  |
                < d' a f > 1 -\tenuto 
                % warning: overlong bar truncated here |
                R1  |
%% 50
                < bes d' f > 1 -\tenuto 
                % warning: overlong bar truncated here |
                r2 r2  |
                < d' a f > 1 -\tenuto 
                % warning: overlong bar truncated here |
                R1  |
                < bes d' f > 1 -\tenuto 
                % warning: overlong bar truncated here |
%% 55
                r2 r4 r4  |
                < d' a f > 1 -\tenuto 
                % warning: overlong bar truncated here |
                R1  |
                < bes d' f > 1 -\tenuto 
                % warning: overlong bar truncated here |
                r2 r2  |
%% 60
                < d' a f > 1 -\tenuto 
                % warning: overlong bar truncated here |
                R1  |
                < bes d' f > 1 -\tenuto 
                % warning: overlong bar truncated here |
                r2 r4 r4  |
                < d' a f > 1 -\tenuto 
                % warning: overlong bar truncated here |
%% 65
                R1  |
                < bes d' f > 1 -\tenuto 
                % warning: overlong bar truncated here |
                r2 r2  |
                < d' a f > 1 -\tenuto 
                % warning: overlong bar truncated here |
                r2 r4 r16 r64 
                % warning: bar too short, padding with rests
                % 53/64 < 4/4
                r64 r32 r8  |
            } % Voice
        >> % Staff

        \context Staff = "track 4" << 
            \set Staff.instrumentName = \markup { \column { "lead1 " } }
            \set Staff.midiInstrument = ""
            \set Score.skipBars = ##t
            \set Staff.printKeyCancellation = ##f
            \new Voice \global
            \new Voice \globalTempo

            \context Voice = "voice 4" {
                \override Voice.TextScript #'padding = #2.0
                \override MultiMeasureRest #'expand-limit = 1

                \time 4/4
                \clef "treble"
                \key bes \major
                R1*7  |
                r8 r16 bes' 2. 
                % warning: overlong bar truncated here
                % warning: bar too short, padding with rests
                % 15/16 < 4/4
                 |
                R1  |
%% 10
                r8 
                % warning: bar too short, padding with rests
                % 1/8 < 4/4
                r8 r4 r2  |
                r2 r4 
                % warning: bar too short, padding with rests
                % 3/4 < 4/4
                r4  |
                r16 c'' 2... -\tenuto 
                % warning: overlong bar truncated here |
                r16 r16 r8 r4 d'' 2  |
                c'' 4 -\tenuto r16 a' 4 -\tenuto r16 c'' 4. -\tenuto 
                % warning: overlong bar truncated here |
%% 15
                r8 r8 r bes' 16 r c'' 4 d'' 8 -\tenuto r16 r32 d'' -\tenuto  |
                R1*2  |
                R1  |
                r4 \times 2/3 { r8 a'' -\staccato r } r r16 bes'' 4 -\tenuto 
                % warning: overlong bar truncated here
                % warning: bar too short, padding with rests
                % 15/16 < 4/4
                 |
                r2 r16 a'' r r32 g'' 16. r8 
                % warning: bar too short, padding with rests
                % 15/16 < 4/4
                r16  |
%% 20
                a'' 8. -\tenuto bes'' 4 -\tenuto r16 c''' 4 -\tenuto r16 r32 bes'' 8 -\tenuto 
                % warning: bar too short, padding with rests
                % 31/32 < 4/4
                r32  |
                r2 r8 g'' 4 r8  |
                g'' 1 -\tenuto 
                % warning: overlong bar truncated here |
                R1*2  |
                R1  |
%% 25
                r4 \times 2/3 { r8 r g' } a' bes' -\tenuto a' 16 -\tenuto g' 8. -\tenuto  |
                r32 r64 a' 32 -\staccato bes' 4.. -\tenuto c'' 4. r8  |
                r4 r8 c'' 8 -\staccato bes' 4 -\tenuto \times 2/3 { r8 a' r }  |
                R1  |
                r4 \times 2/3 { r8 r g' } g' 4 -\tenuto r16 r32 bes' 8 r32  |
%% 30
                R1  |
                r2 r4 r16 c'' -\tenuto < d'' e'' > -\tenuto r  |
                r4 r16 ees'' 2 r16 r8  |
                r4 r16 r32 c'' -\tenuto d'' -\tenuto e'' 16 r32 ees'' 8 d'' 16. r32 r c'' 8 -\staccato \times 2/3 { r16 c'' r ) }  |
                bes' 1 
                % warning: overlong bar truncated here |
%% 35
                r2 r4 \times 2/3 { r8 r ees'' -\staccato }  |
                c'' 4 -\tenuto r8 d'' 16 r ees'' 4 -\tenuto \times 2/3 { r8 d'' -\staccato r }  |
                r4 \times 2/3 { r8 bes' r } a' 16. -\tenuto bes' 8 -\staccato r32 c'' 8. r16  |
                R1*3 r2 r4 r8  |
                R1*3  |
%% 40
                R1*2  |
                R1  |
                r4 r8 r8 r2  |
                r2 r32 ges'' 8.. -\tenuto g'' 4  |
                f'' 1  |
%% 45
                r4 r8 ees'' 8 -\tenuto d'' 4 -\tenuto c''  |
                c'' 2 -\tenuto bes' -\tenuto 
                % warning: overlong bar truncated here |
                R1*2  |
                R1 r2  |
                r2 r2  |
%% 50
                R1*2  |
                R1  |
                bes'' 2. -\tenuto r8 ees'' 
                % warning: overlong bar truncated here |
                r4 r8 r8 r16 r32 g'' 8 -\tenuto r32 a'' 16. r32 r8  |
                R1*2  |
%% 55
                R1  |
                d'' 4. -\tenuto ees'' r4  |
                f'' 4. ees'' 4 -\tenuto d'' 8. -\tenuto c'' 8 -\tenuto r16  |
                R1  |
                r2 r8 a' 8.. -\tenuto g' 8 -\tenuto r32  |
%% 60
                r8 r32 bes' 8 -\tenuto r32 a' 8. g' 2 
                % warning: overlong bar truncated here |
                R1*2  |
                R1 r2  |
                r2 r2  |
                r2 r  |
%% 65
                r2 r  |
                R1  |
                r2 r32 bes'' 16 -\staccato r32 r8 r16 a'' 64 -\tenuto 
                % warning: bar too short, padding with rests
                % 53/64 < 4/4
                r64 r32 r8  |
            } % Voice
        >> % Staff

        \context Staff = "track 5" << 
            \set Staff.instrumentName = \markup { \column { "pad2 " } }
            \set Staff.midiInstrument = ""
            \set Score.skipBars = ##t
            \set Staff.printKeyCancellation = ##f
            \new Voice \global
            \new Voice \globalTempo

            \context Voice = "voice 5" {
                \override Voice.TextScript #'padding = #2.0
                \override MultiMeasureRest #'expand-limit = 1

                \time 4/4
                \clef "alto"
                \key bes \major
                R1*9  |
%% 10
                < f'' d''' bes'' f d' bes > 1 
                % warning: overlong bar truncated here |
                R1  |
                < d''' a'' f'' d' a f > 1 
                % warning: overlong bar truncated here |
                R1  |
                < bes'' d''' f'' bes d' f > 1 
                % warning: overlong bar truncated here |
%% 15
                r2 r4 r8 r16 < a'' d''' > 16 -\tenuto  |
                < f'' a d' f > 1 -\tenuto 
                % warning: overlong bar truncated here |
                r2 r4 r4  |
                < f d' bes > 1 
                % warning: overlong bar truncated here |
                R1  |
%% 20
                < d''' a'' f'' d' a f > 1 
                % warning: overlong bar truncated here |
                R1  |
                < bes'' d''' f'' bes d' f > 1 
                % warning: overlong bar truncated here |
                r2 r4 r8 r16 < a'' d''' > 16 -\tenuto  |
                < f'' a d' f > 1 -\tenuto 
                % warning: overlong bar truncated here |
%% 25
                r2 r4 r4  |
                < f d' bes > 1 
                % warning: overlong bar truncated here |
                R1  |
                < d''' a'' f'' d' a f > 1 
                % warning: overlong bar truncated here |
                R1  |
%% 30
                < bes'' d''' f'' bes d' f > 1 
                % warning: overlong bar truncated here |
                r2 r4 r8 r16 < a'' d''' > 16 -\tenuto  |
                < f'' a d' f > 1 -\tenuto 
                % warning: overlong bar truncated here |
                r2 r4 r4  |
                < f d' bes > 1 
                % warning: overlong bar truncated here |
%% 35
                R1  |
                < d''' a'' f'' d' a f > 1 
                % warning: overlong bar truncated here |
                R1  |
                < bes'' d''' f'' bes d' f > 1 
                % warning: overlong bar truncated here |
                r2 r4 r8 r16 < a'' d''' > 16 -\tenuto  |
%% 40
                < f'' a d' f > 1 -\tenuto 
                % warning: overlong bar truncated here |
                r2 r4 r4  |
                < bes f d' > 1  |
                < d' aes f > 1  |
                < a c' e > 2. r4  |
%% 45
                < bes g ees > 1  |
                < bes d' f > 1 -\tenuto 
                % warning: overlong bar truncated here |
                r2 r4 r4  |
                < d' a f > 1 -\tenuto 
                % warning: overlong bar truncated here |
                R1  |
%% 50
                < bes d' f > 1 -\tenuto 
                % warning: overlong bar truncated here |
                r2 r2  |
                < d' a f > 1 -\tenuto 
                % warning: overlong bar truncated here |
                R1  |
                < bes d' f > 1 -\tenuto 
                % warning: overlong bar truncated here |
%% 55
                r2 r4 r4  |
                < d' a f > 1 -\tenuto 
                % warning: overlong bar truncated here |
                R1  |
                < bes d' f > 1 -\tenuto 
                % warning: overlong bar truncated here |
                r2 r2  |
%% 60
                < d' a f > 1 -\tenuto 
                % warning: overlong bar truncated here |
                R1  |
                < bes d' f > 1 -\tenuto 
                % warning: overlong bar truncated here |
                r2 r4 r4  |
                < d' a f > 1 -\tenuto 
                % warning: overlong bar truncated here |
%% 65
                R1  |
                < bes d' f > 1 -\tenuto 
                % warning: overlong bar truncated here |
                r2 r2  |
                < d' a f > 1 -\tenuto 
                % warning: overlong bar truncated here |
                r2 r4 r16 r64 
                % warning: bar too short, padding with rests
                % 53/64 < 4/4
                r64 r32 r8  |
            } % Voice
        >> % Staff

        \context Staff = "track 6" << 
            \set Staff.instrumentName = \markup { \column { "rhodes tremolo " } }
            \set Staff.midiInstrument = ""
            \set Score.skipBars = ##t
            \set Staff.printKeyCancellation = ##f
            \new Voice \global
            \new Voice \globalTempo

            \context Voice = "voice 6" {
                \override Voice.TextScript #'padding = #2.0
                \override MultiMeasureRest #'expand-limit = 1

                \time 4/4
                \clef "alto"
                \key bes \major
                R1*9  |
%% 10
                < bes bes' > 1 
                % warning: overlong bar truncated here |
                R1  |
                < a a' > 1 
                % warning: overlong bar truncated here |
                R1  |
                < bes bes' > 1 
                % warning: overlong bar truncated here |
%% 15
                R1  |
                < a a' > 1 -\tenuto 
                % warning: overlong bar truncated here |
                r2 r4 r4  |
                < bes bes' > 1 
                % warning: overlong bar truncated here |
                R1  |
%% 20
                < a a' > 1 
                % warning: overlong bar truncated here |
                R1  |
                < bes bes' > 1 
                % warning: overlong bar truncated here |
                R1  |
                < a a' > 1 -\tenuto 
                % warning: overlong bar truncated here |
%% 25
                r2 r4 r4  |
                < bes bes' > 1 
                % warning: overlong bar truncated here |
                R1  |
                < a a' > 1 
                % warning: overlong bar truncated here |
                R1  |
%% 30
                < bes bes' > 1 
                % warning: overlong bar truncated here |
                R1  |
                < a a' > 1 -\tenuto 
                % warning: overlong bar truncated here |
                r2 r4 r4  |
                < bes bes' > 1 
                % warning: overlong bar truncated here |
%% 35
                R1  |
                < a a' > 1 
                % warning: overlong bar truncated here |
                R1  |
                < bes bes' > 1 
                % warning: overlong bar truncated here |
                R1  |
%% 40
                < a a' > 1 -\tenuto 
                % warning: overlong bar truncated here |
            } % Voice
        >> % Staff (final)
    >> % notes

    \layout { }
    \midi {
        \tempo 4 = 120
    } 
} % score
