% This LilyPond file was generated by Rosegarden 1.5.1
\version "2.6.0"
% point and click debugging is enabled
\header {
    copyright = "Unknown"
    subtitle = "blank"
    title = "Untitled"
    tagline = "Created using Rosegarden 1.5.1 and LilyPond"
}
#(set-global-staff-size 16)
#(set-default-paper-size "a4")
global = { 
    \time 4/4
    \skip 1*93  %% 1-94
}
globalTempo = {
    \tempo 4 = 120  \skip 1*92 \skip 2 \skip 4 \skip 8 
}
\score {
    \new StaffGroup <<
        % force offset of colliding notes in chords:
        \override Score.NoteColumn #'force-hshift = #1.0

        \context Staff = "track 3" << 
            \set Staff.instrument = "elotroyo"
            \set Staff.midiInstrument = "Fingered Bass"
            \set Score.skipBars = ##t
            \set Staff.printKeyCancellation = ##f
            \new Voice \global
            \new Voice \globalTempo

            \context Voice = "voice 1" {
                \override Voice.TextScript #'padding = #2.0                \override MultiMeasureRest #'expand-limit = 1

                
                \clef "bass"
                \key c \minor
                c 16 r r8 d 16 r r8 c r r4  |
                c 16 r r8 d 16 r r8 c 16 c 8. c 16 [ c c c ]  |
                a, 8 [ a, a, a, ] a, [ a, a, a, ]  |
%% 5
                g, 8 [ g, g, g, ] g, [ g, g, g, ]  |
                a, 8 [ a, a, a, ] a, [ a, a, a, ]  |
                g, 8 [ g, g, g, ] f, [ f, f, f, ]  |
                a, 8 [ a, a, a, ] a, [ a, a, a, ]  |
                g, 8 [ g, g, g, ] g, [ g, g, g, ]  |
%% 10
                a, 8 [ a, a, a, ] a, [ a, a, a, ]  |
                g, 8 [ g, g, g, ] f, [ f, f, f, ]  |
                a, 8 [ a, a, a, ] a, [ a, a, a, ]  |
                g, 8 [ g, g, g, ] g, [ g, g, g, ]  |
                a, 8 [ a, a, a, ] a, [ a, a, a, ]  |
%% 15
                g, 8 [ g, g, g, ] f, [ f, f, f, ]  |
                a, 8 [ a, a, a, ] a, [ a, a, a, ]  |
                g, 8 [ g, g, g, ] g, [ g, g, g, ]  |
                a, 8 [ a, a, a, ] a, [ a, a, a, ]  |
                g, 8 [ g, g, g, ] f, [ f, f, f, ]  |
%% 20
                f, 8 [ f, f, f, ] f, [ f, f, f, ]  |
                d, 8 [ d, d, d, ] d, [ d, d, d, ]  |
                f, 8 [ f, f, f, ] f, [ f, f, f, ]  |
                e, 8 [ e, e, e, ] e, [ e, e, e, ]  |
                f, 8 [ f, f, f, ] f, [ f, f, f, ]  |
%% 25
                d, 8 [ d, d, d, ] d, [ d, d, d, ]  |
                f, 8 [ f, f, f, ] f, [ f, f, f, ]  |
                g, 8 [ g, g, g, ] g, [ g, g, g, ]  |
                a, 8 [ a, a, a, ] a, [ a, a, a, ]  |
                g, 8 [ g, g, g, ] g, [ g, g, g, ]  |
%% 30
                a, 8 [ a, a, a, ] a, [ a, a, a, ]  |
                g, 8 [ g, g, g, ] f, [ f, f, f, ]  |
                a, 8 [ a, a, a, ] a, [ a, a, a, ]  |
                g, 8 [ g, g, g, ] g, [ g, g, g, ]  |
                a, 8 [ a, a, a, ] a, [ a, a, a, ]  |
%% 35
                g, 8 [ g, g, g, ] f, [ f, f, f, ]  |
                g, 16 [ g, ] r g, c 8. [ c ] g 4 r8  |
                c, 8 [ g, ] e g, 4. r4  |
                g, 8 [ d ] b d 4. r4  |
                a, 8 [ e ] c' e 4. r4  |
%% 40
                a, 8 [ e ] c' e 4. r4  |
                c, 8 [ g, ] e g, 4. r4  |
                g, 8 [ d ] b d 4. r4  |
                a, 8 [ e ] c' e 4. r4  |
                a, 8 [ e ] c' e 4. r4  |
%% 45
                c, 8 [ g, ] e g, 4. r4  |
                g, 8 [ d ] b d 4. r4  |
                a, 8 [ e ] c' e 4. r4  |
                a, 8 [ e ] c' e 4. r4  |
                c, 8 [ g, ] e g, 4. r4  |
%% 50
                g, 8 [ d ] b d 4. r4  |
                a, 8 [ e ] c' e 4. r4  |
                a, 8 [ e ] c' e 4. r4  |
                f, 8 [ f, f, f, ] f, [ f, f, f, ]  |
                d, 8 [ d, d, d, ] d, [ d, d, d, ]  |
%% 55
                f, 8 [ f, f, f, ] f, [ f, f, f, ]  |
                e, 8 [ e, e, e, ] e, [ e, e, e, ]  |
                f, 8 [ f, f, f, ] f, [ f, f, f, ]  |
                d, 8 [ d, d, d, ] d, [ d, d, d, ]  |
                f, 8 [ f, f, f, ] f, [ f, f, f, ]  |
%% 60
                g, 8 [ g, g, g, ] g, [ g, g, g, ]  |
                a, 8 [ a, a, a, ] a, [ a, a, a, ]  |
                g, 8 [ g, g, g, ] g, [ g, g, g, ]  |
                a, 8 [ a, a, a, ] a, [ a, a, a, ]  |
                g, 8 [ g, g, g, ] f, [ f, f, f, ]  |
%% 65
                a, 8 [ a, a, a, ] a, [ a, a, a, ]  |
                g, 8 [ g, g, g, ] g, [ g, g, g, ]  |
                a, 8 [ a, a, a, ] a, [ a, a, a, ]  |
                g, 8 [ g, g, g, ] f, [ f, f, f, ]  |
                a, 8 [ a, a, a, ] a, [ a, a, a, ]  |
%% 70
                g, 8 [ g, g, g, ] g, [ g, g, g, ]  |
                a, 8 [ a, a, a, ] a, [ a, a, a, ]  |
                g, 8 [ g, g, g, ] f, [ f, f, f, ]  |
                a, 8 [ a, a, a, ] a, [ a, a, a, ]  |
                g, 8 [ g, g, g, ] g, [ g, g, g, ]  |
%% 75
                a, 8 [ a, a, a, ] a, [ a, a, a, ]  |
                g, 8 [ g, g, g, ] f, [ f, f, f, ]  |
                g, 16 [ g, ] r g, c 8. [ c ] g 4 r8  |
                c, 8 [ g, ] e g, 4. r4  |
                g, 8 [ d ] b d 4. r4  |
%% 80
                a, 8 [ e ] c' e 4. r4  |
                a, 8 [ e ] c' e 4. r4  |
                c, 8 [ g, ] e g, 4. r4  |
                g, 8 [ d ] b d 4. r4  |
                a, 8 [ e ] c' e 4. r4  |
%% 85
                a, 8 [ e ] c' e 4. r4  |
                c, 8 [ g, ] e g, 4. r4  |
                g, 8 [ d ] b d 4. r4  |
                a, 8 [ e ] c' e 4. r4  |
                a, 8 [ e ] c' e 4. r4  |
%% 90
                c, 8 [ g, ] e g, 4. r4  |
                g, 8 [ d ] b d 4. r4  |
                a, 8 [ e ] c' e 4. r4  |
                a, 8 [ e ] c' e 4. r4  |
                g, 16 [ g, ] r g, c 8. [ c ] g 4 
                % warning: bar too short, padding with rests
                r8  |
                \bar "|."
            } % Voice
        >> % Staff (final)
    >> % notes

    \layout { }
    \midi {
        \tempo 4 = 120
    } 
} % score
