% This LilyPond file was generated by Rosegarden 1.5.1
\version "2.10.10"
% point and click debugging is enabled
\header {
    copyright = "Unknown"
    subtitle = "blank"
    title = "Untitled"
    tagline = "Created using Rosegarden 1.5.1 and LilyPond"
}
#(set-global-staff-size 16)
#(set-default-paper-size "a4")
global = { 
    \time 4/4
    \skip 1*93  %% 1-94
}
globalTempo = {
    \override Score.MetronomeMark #'transparent = ##t
    \tempo 4 = 120  \skip 1*92 \skip 2 \skip 4 \skip 8 
}
\score {
    <<
        % force offset of colliding notes in chords:
        \override Score.NoteColumn #'force-hshift = #1.0

        \context Staff = "track 1" << 
            \set Staff.instrumentName = "ale"
            \set Staff.midiInstrument = "Distortion Guitar"
            \set Score.skipBars = ##t
            \set Staff.printKeyCancellation = ##f
            \new Voice \global
            \new Voice \globalTempo

            \context Voice = "voice 1" {
                \override Voice.TextScript #'padding = #2.0                \override MultiMeasureRest #'expand-limit = 1

                
                \clef "treble"
                \key c \minor
                c'' 16 b' a' g' a' r a' r c'' 4 -\tenuto r  |
                c'' 16 b' a' g' a' r a' r c'' c'' 4 -\tenuto r16 r8  |
                r4 r8 a' 2 -\tenuto 
                % warning: overlong bar truncated here |
%% 5
                r4 r8 r8 g' 2 
                % warning: overlong bar truncated here |
                r4 r8 r8 r2  |
                r2 r  |
                r8 d'' 2 -\tenuto r8 r4  |
                a' 2 g'' 4 r16 c''' 8. -\tenuto 
                % warning: overlong bar truncated here |
%% 10
                r4 r16 r16 r8 r2  |
                r2 r  |
                r4 r8 a' 2 -\tenuto 
                % warning: overlong bar truncated here |
                r4 r8 r8 g' 2 
                % warning: overlong bar truncated here |
                r4 r8 r8 r2  |
%% 15
                r2 r  |
                r8 d'' 2 -\tenuto r8 r4  |
                a' 2 g'' 4 r16 c''' 8. -\tenuto 
                % warning: overlong bar truncated here |
                r4 r16 r16 r8 r2  |
                r2 r4 a' 16 b' c'' d''  |
%% 20
                e'' 4 r a'' 8 e'' a'' e''  |
                r4 d''' 8 a'' 4 d''' f''' 8 
                % warning: overlong bar truncated here |
                r4 r4 r r8 d''' 16 r  |
                f''' 8 d''' c''' a'' 4 g'' 8 f'' 4  |
                e'' 4 r8 d'' 4 -\tenuto r8 r4  |
%% 25
                R1*3  |
                r4 r8 a' 2 -\tenuto 
                % warning: overlong bar truncated here |
                r4 r8 r8 g' 2 
                % warning: overlong bar truncated here |
%% 30
                r4 r8 r8 r2  |
                r2 r  |
                r8 d'' 2 -\tenuto r8 r4  |
                a' 2 g'' 4 r16 c''' 8. -\tenuto 
                % warning: overlong bar truncated here |
                r4 r16 r16 r8 r2  |
%% 35
                r2 r  |
                g' 16 g' r g' c'' 8. c'' g'' 4 r8  |
                r2 r4 r8 g''  |
                g'' 8 f'' e'' f'' 4 e'' d'' 8 
                % warning: overlong bar truncated here |
                r4 r4 r r8 c''  |
%% 40
                c'' 8 d'' e'' d'' 4 e'' f'' 8 
                % warning: overlong bar truncated here |
                r4 r4 r2  |
                g'' 8 f'' e'' f'' 4 e'' d'' 8 
                % warning: overlong bar truncated here |
                r4 r4 r r8 c''  |
                c'' 8 d'' e'' d'' 4 e'' f'' 8 
                % warning: overlong bar truncated here |
%% 45
                r4 r8 f'' 4 e'' d'' 8 
                % warning: overlong bar truncated here |
                r4 r4 r r8 c''  |
                c'' 8 d'' e'' d'' 4 e'' f'' 8 
                % warning: overlong bar truncated here |
                r4 r4 r2  |
                g'' 8 f'' e'' f'' 4 e'' d'' 8 
                % warning: overlong bar truncated here |
%% 50
                r4 r4 r r8 c''  |
                c'' 8 d'' e'' d'' 4 e'' f'' 8 
                % warning: overlong bar truncated here |
                r4 r4 r a' 16 b' c'' d''  |
                e'' 4 r a'' 8 e'' a'' e''  |
                r4 d''' 8 a'' 4 d''' f''' 8 
                % warning: overlong bar truncated here |
%% 55
                r4 r4 r r8 d''' 16 r  |
                f''' 8 d''' c''' a'' 4 g'' 8 f'' 4  |
                e'' 4 r8 d'' 4 -\tenuto r8 r4  |
                R1*3  |
                r4 r8 a' 2 -\tenuto 
                % warning: overlong bar truncated here |
                r4 r8 r8 g' 2 
                % warning: overlong bar truncated here |
                r4 r8 r8 r2  |
                r2 r  |
%% 65
                r8 d'' 2 -\tenuto r8 r4  |
                a' 2 g'' 4 r16 c''' 8. -\tenuto 
                % warning: overlong bar truncated here |
                r4 r16 r16 r8 r2  |
                r2 r  |
                r4 r8 a' 2 -\tenuto 
                % warning: overlong bar truncated here |
%% 70
                r4 r8 r8 g' 2 
                % warning: overlong bar truncated here |
                r4 r8 r8 r2  |
                r2 r  |
                r8 d'' 2 -\tenuto r8 r4  |
                a' 2 g'' 4 r16 c''' 8. -\tenuto 
                % warning: overlong bar truncated here |
%% 75
                r4 r16 r16 r8 r2  |
                r2 r  |
                g' 16 g' r g' c'' 8. c'' g'' 4 r8  |
                r2 r4 r8 g''  |
                g'' 8 f'' e'' f'' 4 e'' d'' 8 
                % warning: overlong bar truncated here |
%% 80
                r4 r4 r r8 c''  |
                c'' 8 d'' e'' d'' 4 e'' f'' 8 
                % warning: overlong bar truncated here |
                r4 r4 r2  |
                g'' 8 f'' e'' f'' 4 e'' d'' 8 
                % warning: overlong bar truncated here |
                r4 r4 r r8 c''  |
%% 85
                c'' 8 d'' e'' d'' 4 e'' f'' 8 
                % warning: overlong bar truncated here |
                r4 r8 f'' 4 e'' d'' 8 
                % warning: overlong bar truncated here |
                r4 r4 r r8 c''  |
                c'' 8 d'' e'' d'' 4 e'' f'' 8 
                % warning: overlong bar truncated here |
                r4 r4 r2  |
%% 90
                g'' 8 f'' e'' f'' 4 e'' d'' 8 
                % warning: overlong bar truncated here |
                r4 r4 r r8 c''  |
                c'' 8 d'' e'' d'' 4 e'' f'' 8 
                % warning: overlong bar truncated here |
                r4 r4 r2  |
                g' 16 g' r g' c'' 8. c'' g'' 4 
                % warning: bar too short, padding with rests
                r8  |
                \bar "|."
            } % Voice
        >> % Staff (final)
    >> % notes

    \layout { }
    
  \midi {
    \context {
      \Score
      tempoWholesPerMinute = #(ly:make-moment 120 4)
      }
    }

 
} % score
