% This LilyPond file was generated by Rosegarden 11.06
\include "nederlands.ly"
\version "2.12.0"
\header {
    copyright = "Copyright (c) 2008 Zajaro"
    subtitle = "not yet subtitled"
    title = "Chiara's 80's"
    tagline = "Created using Rosegarden 11.06 and LilyPond"
}
#(set-global-staff-size 16)
#(set-default-paper-size "a4")
chExceptionMusic = { <c e>-\markup { \super "3"} }
chExceptions = #(append (sequential-music-to-chord-exceptions chExceptionMusic #t) ignatzekExceptions)
global = { 
    \time 4/4
    \skip 1*92 \skip 2 \skip 4  %% 1-94
}
globalTempo = {
    \tempo 4 = 120  \skip 1*92 \skip 2 \skip 4 
}
markers = {
}
\score {
<< % common
        % force offset of colliding notes in chords:
        \override Score.NoteColumn #'force-hshift = #1.0

        \context Staff = "track 1, trackB:channelA" << 
            \set Staff.instrumentName = \markup { \column { "trackB:channelA " } }
            \set Staff.midiInstrument = "SynthBrass 1"
            \set Score.skipBars = ##t
            \set Staff.printKeyCancellation = ##f
            \new Voice \global
            \new Voice \globalTempo
            \new Voice \markers

            \context Voice = "voice 1" {
                \override Voice.TextScript #'padding = #2.0
                \override MultiMeasureRest #'expand-limit = 1

                
                \clef "treble"
                \key c \major
                c'' 16 [ b' a' g' ] a' 8 [ a' ] c'' 4 r  |
                c'' 16 [ b' a' g' ] a' 8 [ a' ] c'' 16 c'' 4..  |
                r4 r8 a' 2 r8  |
%% 5
                r4 r8 g' 2 r8  |
                R1*2  |
                d'' 2 r4 r8 a' 
                % warning: overlong bar truncated here |
                \skip 4 \skip 8 g'' 4 r16 c''' 8. r8  |
%% 10
                R1*2  |
                r4 a' 2 -\tenuto r4  |
                r4 r8 g' 2 r8  |
                R1*2  |
                d'' 2 r4 r8 a' 
                % warning: overlong bar truncated here |
                \skip 4 \skip 8 g'' 4 r16 c''' 8. r8  |
                R1  |
                r2 r8 [ a' 16 b' ] c'' [ d'' ] e'' 8 
                % warning: overlong bar truncated here |
%% 20
                \skip 8 r8 r [ a'' e'' a'' ] e'' r  |
                r8 d''' a'' 4 d''' f''' 8 r  |
                r2 r4 d''' 16 r f''' 8  |
                d''' 8 [ c''' ] a'' 4 g'' 8 f'' 4 e'' 8 
                % warning: overlong bar truncated here |
                \skip 8 r8 d'' 4 r2  |
%% 25
                r2 r  |
                r2 r  |
                r2 r  |
                r4 a' 2 r4  |
                r4 g' 2 r4  |
%% 30
                R1  |
                r2 r4 r8 d'' 
                % warning: overlong bar truncated here |
                \skip 4 \skip 8 r8 r4 a' 
                % warning: overlong bar truncated here |
                \skip 4 g'' 4 r16 c''' 8. r4  |
                R1  |
%% 35
                r2 r4 g' 16 [ g' ] r g'  |
                c'' 8. [ c'' ] g'' 4 r8 r4  |
                r2 r8 [ g'' g'' f'' ]  |
                e'' 8 f'' 4 e'' d'' 8 r4  |
                r2 r8 [ c'' c'' d'' ]  |
%% 40
                e'' 8 d'' 4 e'' f'' 8 r4  |
                r2 r4 g'' 8 [ f'' ]  |
                e'' 8 f'' 4 e'' d'' 8 r4  |
                r2 r8 [ c'' c'' d'' ]  |
                e'' 8 d'' 4 e'' f'' 8 r4  |
%% 45
                r8 f'' 4 e'' d'' 8 r4  |
                r2 r8 [ c'' c'' d'' ]  |
                e'' 8 d'' 4 e'' f'' 8 r4  |
                r2 r4 g'' 8 [ f'' ]  |
                e'' 8 f'' 4 e'' d'' 8 r4  |
%% 50
                r2 r8 [ c'' c'' d'' ]  |
                e'' 8 d'' 4 e'' f'' 8 r4  |
                r2 a' 16 [ b' c'' d'' ] e'' 4  |
                r4 a'' 8 [ e'' a'' e'' ] r4  |
                d''' 8 a'' 4 d''' f''' 8 r4  |
%% 55
                r2 r8 d''' 16 r f''' 8 [ d''' ]  |
                c''' 8 a'' 4 g'' 8 f'' 4 e''  |
                r8 d'' 4 r8 r2  |
                r2 r  |
                r2 r  |
%% 60
                r2 r  |
                r8 a' 2 r8 r4  |
                r8 g' 2 r8 r4  |
                R1  |
                r2 r4 d'' 
                % warning: overlong bar truncated here |
%% 65
                \skip 4 r4 r8 a' 4. 
                % warning: overlong bar truncated here |
                \skip 8 g'' 4 r16 c''' 8. r8 r4  |
                R1*2  |
                a' 2 r  |
%% 70
                g' 2 r  |
                r2 r  |
                r2 r8 d'' 4. 
                % warning: overlong bar truncated here |
                \skip 8 r8 r4 a' 2  |
                g'' 4 r16 c''' 8. r2  |
%% 75
                r2 r  |
                r2 g' 16 [ g' ] r g' c'' 8. [ c'' 16 ] 
                % warning: overlong bar truncated here |
                \skip 8 g'' 4 r8 r2  |
                r4 r8 [ g'' g'' f'' ] e'' f'' 
                % warning: overlong bar truncated here |
                \skip 8 e'' 4 d'' 8 r2  |
%% 80
                r4 r8 [ c'' c'' d'' ] e'' d'' 
                % warning: overlong bar truncated here |
                \skip 8 e'' 4 f'' 8 r2  |
                r2 g'' 8 [ f'' ] e'' f'' 
                % warning: overlong bar truncated here |
                \skip 8 e'' 4 d'' 8 r2  |
                r4 r8 [ c'' c'' d'' ] e'' d'' 
                % warning: overlong bar truncated here |
%% 85
                \skip 8 e'' 4 f'' 8 r4 r8 f'' 
                % warning: overlong bar truncated here |
                \skip 8 e'' 4 d'' 8 r2  |
                r4 r8 [ c'' c'' d'' ] e'' d'' 
                % warning: overlong bar truncated here |
                \skip 8 e'' 4 f'' 8 r2  |
                r2 g'' 8 [ f'' ] e'' f'' 
                % warning: overlong bar truncated here |
%% 90
                \skip 8 e'' 4 d'' 8 r2  |
                r4 r8 [ c'' c'' d'' ] e'' d'' 
                % warning: overlong bar truncated here |
                \skip 8 e'' 4 f'' 8 r2  |
                r2 g' 16 [ g' ] r g' c'' 8. [ c'' 16 ] 
                % warning: overlong bar truncated here |
                \skip 8 g'' 4  |
            } % Voice
        >> % Staff ends

        \context Staff = "track 2, trackC:channelA" << 
            \set Staff.instrumentName = \markup { \column { "trackC:channelA " } }
            \set Staff.midiInstrument = "Pad 2 (warm)"
            \set Score.skipBars = ##t
            \set Staff.printKeyCancellation = ##f
            \new Voice \global
            \new Voice \globalTempo
            \new Voice \markers

            \context Voice = "voice 2" {
                \override Voice.TextScript #'padding = #2.0
                \override MultiMeasureRest #'expand-limit = 1

                
                \clef "alto"
                \key c \major
                c'' 16 [ b' a' g' ] a' 8 [ a' ] < c' g' e' > 4 r  |
                c'' 16 [ b' a' g' ] a' 8 [ a' ] < g' c' e' > 16 [ < c' e' g' > ] r8 r4  |
                < a c' e' > 4. < b d' g > r4  |
%% 5
                < f a c' > 4 r8 < g' e' c' > 4 < e' g' b' > r8  |
                < a c' e' > 4. < g d' b > r4  |
                < f a c' > 4 r8 [ < g' c' e' > ] < c' e' g' > < e' g' b' > 4 < g' b' e' > 8  |
                < a c' e' > 4. < g b d' > r4  |
                < f a c' > 4 r8 < c' e' g' > 4 < e' b' g' > r8  |
%% 10
                < a c' e' > 4. < g b d' > r4  |
                < f a c' > 4 r8 < c' e' g' > 4 < e' g' b' > < e' g' b' > 8  |
                < e' a c' > 4. < g b d' > r4  |
                < c' a f > 4 r8 < c' e' g' > 4 < g' b' e' > r8  |
                < a c' e' > 4. < g b d' > r4  |
%% 15
                < f a c' > 4 r8 < c' e' g' > 4 < e' g' b' > < e' g' b' > 8  |
                < a c' e' > 4. < g d' b > r4  |
                < f a c' > 4 r8 < g' c' e' > 4 < e' g' b' > r8  |
                < c' e' a > 4. < g b d' > r4  |
                < c' a f > 4 r8 < c' e' g' > 4 < e' g' b' > < e' b' g' > 8  |
%% 20
                < f' a' c'' > 4. < f' a' c'' > 4 < f' a' c'' > < f' a' c'' > 8  |
                < f' a' d' > 4. < d' f' a' > 4 < a' d' f' > < d' f' a' > 8  |
                < f' a' c'' > 4. < f' a' c'' > 4 < f' a' c'' > < f' a' c'' > 8  |
                < b' e' g' > 4. < e' g' b' > 4 < g' b' e' > < e' g' b' > 8  |
                < f' a' c'' > 4. < c'' f' a' > 4 < f' a' c'' > < c'' a' f' > 8  |
%% 25
                < d' f' a' > 4. < d' f' a' > 4 < d' f' a' > < d' f' a' > 8  |
                < a' c'' f' > 4. < f' a' c'' > 4 < c'' f' a' > < f' a' c'' > 8  |
                < g' b' d'' > 4. < g' b' d'' > 4 < g' b' d'' > < g' b' d'' > 8  |
                < e' a c' > 4. < g b d' > r4  |
                < a c' f > 4 r8 < c' e' g' > 4 < b' e' g' > r8  |
%% 30
                < a c' e' > 4. < g b d' > r4  |
                < f a c' > 4 r8 < c' e' g' > 4 < e' g' b' > < e' g' b' > 8  |
                < c' e' a > 4. < g b d' > r4  |
                < c' a f > 4 r8 < e' g' c' > 4 < e' g' b' > r8  |
                < a e' c' > 4. < g b d' > r4  |
%% 35
                < c' a f > 4 r8 < c' e' g' > 4 < b' g' e' > < e' g' b' > 8  |
                g' 16 [ g' ] r [ g' ] c'' c'' 8 c'' 16 g'' 4 r  |
                r8 < e' g' c'' > 4 < e' g' c'' > < e' g' c'' > < e' g' c'' > 8  |
                r8 < d' g' b > 4 < b d' g' > < d' g' b > < b d' g' > 8  |
                r8 < c' e' a' > 4 < a' c' e' > < c' e' a' > < e' a' c' > 8  |
%% 40
                r8 < c' e' a' > 4 < c' e' a' > < c' e' a' > < c' e' a' > 8  |
                r8 < g' c'' e' > 4 < e' g' c'' > < c'' g' e' > < g' c'' e' > 8  |
                r8 < b d' g' > 4 < b d' g' > < b d' g' > < b d' g' > 8  |
                r8 < a' c' e' > 4 < c' e' a' > < e' a' c' > < c' e' a' > 8  |
                r8 < c' e' a' > 4 < a' c' e' > < c' e' a' > < a' e' c' > 8  |
%% 45
                r8 < e' g' c'' > 4 < e' g' c'' > < c'' e' g' > < e' g' c'' > 8  |
                r8 < b d' g' > 4 < g' d' b > < b d' g' > < g' d' b > 8  |
                r8 < c' e' a' > 4 < c' e' a' > < c' a' e' > < c' e' a' > 8  |
                r8 < c' e' a' > 4 < a' c' e' > < c' e' a' > < e' a' c' > 8  |
                r8 < e' g' c'' > 4 < e' g' c'' > < e' g' c'' > < e' g' c'' > 8  |
%% 50
                r8 < b d' g' > 4 < b g' d' > < b d' g' > < g' b d' > 8  |
                r8 < c' e' a' > 4 < c' e' a' > < c' e' a' > < c' e' a' > 8  |
                r8 < a' e' c' > 4 < c' e' a' > < c' e' a' > < c' a' e' > 8  |
                < f' a' c'' > 4. < f' a' c'' > 4 < f' a' c'' > < f' a' c'' > 8  |
                < f' a' d' > 4. < d' f' a' > 4 < a' d' f' > < d' f' a' > 8  |
%% 55
                < f' a' c'' > 4. < f' a' c'' > 4 < f' a' c'' > < f' a' c'' > 8  |
                < b' e' g' > 4. < e' g' b' > 4 < g' b' e' > < e' g' b' > 8  |
                < f' a' c'' > 4. < c'' f' a' > 4 < f' a' c'' > < c'' a' f' > 8  |
                < d' f' a' > 4. < d' f' a' > 4 < d' f' a' > < d' f' a' > 8  |
                < a' c'' f' > 4. < f' a' c'' > 4 < c'' f' a' > < f' a' c'' > 8  |
%% 60
                < g' b' d'' > 4. < g' b' d'' > 4 < g' b' d'' > < g' b' d'' > 8  |
                < e' a c' > 4. < g b d' > r4  |
                < a c' f > 4 r8 < c' e' g' > 4 < b' e' g' > r8  |
                < a c' e' > 4. < g b d' > r4  |
                < f a c' > 4 r8 < c' e' g' > 4 < e' g' b' > < e' g' b' > 8  |
%% 65
                < c' e' a > 4. < g b d' > r4  |
                < c' a f > 4 r8 < c' e' g' > 4 < e' g' b' > r8  |
                < a e' c' > 4. < g b d' > r4  |
                < c' f a > 4 r8 < c' e' g' > 4 < g' b' e' > < e' g' b' > 8  |
                < a c' e' > 4. < d' g b > r4  |
%% 70
                < f a c' > 4 r8 < g' e' c' > 4 < e' g' b' > r8  |
                < c' e' a > 4. < g b d' > r4  |
                < a c' f > 4 r8 < c' e' g' > 4 < b' e' g' > < e' g' b' > 8  |
                < a c' e' > 4. < b d' g > r4  |
                < f a c' > 4 r8 < g' e' c' > 4 < e' g' b' > r8  |
%% 75
                < a c' e' > 4. < g d' b > r4  |
                < f a c' > 4 r8 < g' c' e' > 4 < e' g' b' > < b' g' e' > 8  |
                g' 16 [ g' ] r [ g' ] c'' c'' 8 c'' 16 g'' 4 r  |
                r8 < g' c'' e' > 4 < e' g' c'' > < g' c'' e' > < e' g' c'' > 8  |
                r8 < b d' g' > 4 < g' b d' > < b d' g' > < b d' g' > 8  |
%% 80
                r8 < c' a' e' > 4 < c' e' a' > < a' c' e' > < c' e' a' > 8  |
                r8 < c' e' a' > 4 < e' a' c' > < c' e' a' > < a' c' e' > 8  |
                r8 < e' g' c'' > 4 < e' g' c'' > < e' g' c'' > < e' g' c'' > 8  |
                r8 < d' g' b > 4 < b d' g' > < d' g' b > < b d' g' > 8  |
                r8 < c' e' a' > 4 < a' c' e' > < c' e' a' > < e' a' c' > 8  |
%% 85
                r8 < c' e' a' > 4 < c' e' a' > < c' e' a' > < c' e' a' > 8  |
                r8 < g' c'' e' > 4 < e' g' c'' > < c'' g' e' > < g' c'' e' > 8  |
                r8 < b d' g' > 4 < b d' g' > < b d' g' > < b d' g' > 8  |
                r8 < a' c' e' > 4 < c' e' a' > < e' a' c' > < c' e' a' > 8  |
                r8 < c' e' a' > 4 < a' c' e' > < c' e' a' > < a' e' c' > 8  |
%% 90
                r8 < e' g' c'' > 4 < e' g' c'' > < c'' e' g' > < e' g' c'' > 8  |
                r8 < b d' g' > 4 < g' d' b > < b d' g' > < g' d' b > 8  |
                r8 < c' e' a' > 4 < c' e' a' > < c' a' e' > < c' e' a' > 8  |
                r8 < c' e' a' > 4 < a' c' e' > < c' e' a' > < e' a' c' > 8  |
                g' 16 [ g' ] r [ g' ] c'' c'' 8 c'' 16 g'' 4  |
                \bar "|."
            } % Voice
        >> % Staff ends

        \context Staff = "track 3, trackD:channelA" << 
            \set Staff.instrumentName = \markup { \column { "trackD:channelA " } }
            \set Staff.midiInstrument = "Slap Bass 1"
            \set Score.skipBars = ##t
            \set Staff.printKeyCancellation = ##f
            \new Voice \global
            \new Voice \globalTempo
            \new Voice \markers

            \context Voice = "voice 3" {
                \override Voice.TextScript #'padding = #2.0
                \override MultiMeasureRest #'expand-limit = 1

                
                \clef "bass_15"
                \key c \major
                c, 4 d, c, r  |
                c, 16 r r8 d, 16 r r8 c, 16 c, 8. c, 16 [ c, c, c, ]  |
                a,, 8 [ a,, a,, a,, ] a,, [ a,, a,, a,, ]  |
%% 5
                g,, 8 [ g,, g,, g,, ] g,, [ g,, g,, g,, ]  |
                a,, 8 [ a,, a,, a,, ] a,, [ a,, a,, a,, ]  |
                g,, 8 [ g,, g,, g,, ] f,, [ f,, f,, f,, ]  |
                a,, 8 [ a,, a,, a,, ] a,, [ a,, a,, a,, ]  |
                g,, 8 [ g,, g,, g,, ] g,, [ g,, g,, g,, ]  |
%% 10
                a,, 8 [ a,, a,, a,, ] a,, [ a,, a,, a,, ]  |
                g,, 8 [ g,, g,, g,, ] f,, [ f,, f,, f,, ]  |
                a,, 8 [ a,, a,, a,, ] a,, [ a,, a,, a,, ]  |
                g,, 8 [ g,, g,, g,, ] g,, [ g,, g,, g,, ]  |
                a,, 8 [ a,, a,, a,, ] a,, [ a,, a,, a,, ]  |
%% 15
                g,, 8 [ g,, g,, g,, ] f,, [ f,, f,, f,, ]  |
                a,, 8 [ a,, a,, a,, ] a,, [ a,, a,, a,, ]  |
                g,, 8 [ g,, g,, g,, ] g,, [ g,, g,, g,, ]  |
                a,, 8 [ a,, a,, a,, ] a,, [ a,, a,, a,, ]  |
                g,, 8 [ g,, g,, g,, ] f,, [ f,, f,, f,, ]  |
%% 20
                f,, 8 [ f,, f,, f,, ] f,, [ f,, f,, f,, ]  |
                d,, 8 [ d,, d,, d,, ] d,, [ d,, d,, d,, ]  |
                f,, 8 [ f,, f,, f,, ] f,, [ f,, f,, f,, ]  |
                e,, 8 [ e,, e,, e,, ] e,, [ e,, e,, e,, ]  |
                f,, 8 [ f,, f,, f,, ] f,, [ f,, f,, f,, ]  |
%% 25
                d,, 8 [ d,, d,, d,, ] d,, [ d,, d,, d,, ]  |
                f,, 8 [ f,, f,, f,, ] f,, [ f,, f,, f,, ]  |
                g,, 8 [ g,, g,, g,, ] g,, [ g,, g,, g,, ]  |
                a,, 8 [ a,, a,, a,, ] a,, [ a,, a,, a,, ]  |
                g,, 8 [ g,, g,, g,, ] g,, [ g,, g,, g,, ]  |
%% 30
                a,, 8 [ a,, a,, a,, ] a,, [ a,, a,, a,, ]  |
                g,, 8 [ g,, g,, g,, ] f,, [ f,, f,, f,, ]  |
                a,, 8 [ a,, a,, a,, ] a,, [ a,, a,, a,, ]  |
                g,, 8 [ g,, g,, g,, ] g,, [ g,, g,, g,, ]  |
                a,, 8 [ a,, a,, a,, ] a,, [ a,, a,, a,, ]  |
%% 35
                g,, 8 [ g,, g,, g,, ] f,, [ f,, f,, f,, ]  |
                g,, 16 [ g,, ] r g,, c, 8. [ c, ] g, 4 r8  |
                c,, 8 [ g,, ] e, g,, 4. r4  |
                g,, 8 [ d, ] b, d, 4. r4  |
                a,, 8 [ e, ] c e, 4. r4  |
%% 40
                a,, 8 [ e, ] c e, 4. r4  |
                c,, 8 [ g,, ] e, g,, 4. r4  |
                g,, 8 [ d, ] b, d, 4. r4  |
                a,, 8 [ e, ] c e, 4. r4  |
                a,, 8 [ e, ] c e, 4. r4  |
%% 45
                c,, 8 [ g,, ] e, g,, 4. r4  |
                g,, 8 [ d, ] b, d, 4. r4  |
                a,, 8 [ e, ] c e, 4. r4  |
                a,, 8 [ e, ] c e, 4. r4  |
                c,, 8 [ g,, ] e, g,, 4. r4  |
%% 50
                g,, 8 [ d, ] b, d, 4. r4  |
                a,, 8 [ e, ] c e, 4. r4  |
                a,, 8 [ e, ] c e, 4. r4  |
                f,, 8 [ f,, f,, f,, ] f,, [ f,, f,, f,, ]  |
                d,, 8 [ d,, d,, d,, ] d,, [ d,, d,, d,, ]  |
%% 55
                f,, 8 [ f,, f,, f,, ] f,, [ f,, f,, f,, ]  |
                e,, 8 [ e,, e,, e,, ] e,, [ e,, e,, e,, ]  |
                f,, 8 [ f,, f,, f,, ] f,, [ f,, f,, f,, ]  |
                d,, 8 [ d,, d,, d,, ] d,, [ d,, d,, d,, ]  |
                f,, 8 [ f,, f,, f,, ] f,, [ f,, f,, f,, ]  |
%% 60
                g,, 8 [ g,, g,, g,, ] g,, [ g,, g,, g,, ]  |
                a,, 8 [ a,, a,, a,, ] a,, [ a,, a,, a,, ]  |
                g,, 8 [ g,, g,, g,, ] g,, [ g,, g,, g,, ]  |
                a,, 8 [ a,, a,, a,, ] a,, [ a,, a,, a,, ]  |
                g,, 8 [ g,, g,, g,, ] f,, [ f,, f,, f,, ]  |
%% 65
                a,, 8 [ a,, a,, a,, ] a,, [ a,, a,, a,, ]  |
                g,, 8 [ g,, g,, g,, ] g,, [ g,, g,, g,, ]  |
                a,, 8 [ a,, a,, a,, ] a,, [ a,, a,, a,, ]  |
                g,, 8 [ g,, g,, g,, ] f,, [ f,, f,, f,, ]  |
                a,, 8 [ a,, a,, a,, ] a,, [ a,, a,, a,, ]  |
%% 70
                g,, 8 [ g,, g,, g,, ] g,, [ g,, g,, g,, ]  |
                a,, 8 [ a,, a,, a,, ] a,, [ a,, a,, a,, ]  |
                g,, 8 [ g,, g,, g,, ] f,, [ f,, f,, f,, ]  |
                a,, 8 [ a,, a,, a,, ] a,, [ a,, a,, a,, ]  |
                g,, 8 [ g,, g,, g,, ] g,, [ g,, g,, g,, ]  |
%% 75
                a,, 8 [ a,, a,, a,, ] a,, [ a,, a,, a,, ]  |
                g,, 8 [ g,, g,, g,, ] f,, [ f,, f,, f,, ]  |
                g,, 16 [ g,, ] r g,, c, 8. [ c, 16 ] g, 4 r  |
                c,, 8 [ g,, ] e, g,, 4. r4  |
                g,, 8 [ d, ] b, d, 4. r4  |
%% 80
                a,, 8 [ e, ] c e, 4. r4  |
                a,, 8 [ e, ] c e, 4. r4  |
                c,, 8 [ g,, ] e, g,, 4. r4  |
                g,, 8 [ d, ] b, d, 4. r4  |
                a,, 8 [ e, ] c e, 4. r4  |
%% 85
                a,, 8 [ e, ] c e, 4. r4  |
                c,, 8 [ g,, ] e, g,, 4. r4  |
                g,, 8 [ d, ] b, d, 4. r4  |
                a,, 8 [ e, ] c e, 4. r4  |
                a,, 8 [ e, ] c e, 4. r4  |
%% 90
                c,, 8 [ g,, ] e, g,, 4. r4  |
                g,, 8 [ d, ] b, d, 4. r4  |
                a,, 8 [ e, ] c e, 4. r4  |
                a,, 8 [ e, ] c e, 4. r4  |
                g,, 16 [ g,, ] r g,, c, 8. [ c, 16 ] g, 4  |
                \bar "|."
            } % Voice
        >> % Staff ends

        \context Staff = "track 4, Imported MIDI" << 
            \set Staff.instrumentName = \markup { \column { "Imported MIDI " } }
            \set Staff.midiInstrument = ""
            \set Score.skipBars = ##t
            \set Staff.printKeyCancellation = ##f
            \new Voice \global
            \new Voice \globalTempo
            \new Voice \markers

            \context Voice = "voice 4" {
                \override Voice.TextScript #'padding = #2.0
                \override MultiMeasureRest #'expand-limit = 1

                \skip 1*2 
                \clef "treble"
                \key c \major
                < c'' e'' a' > 2 < a g' b' d'' >  |
%% 5
                < g f' a' c'' > 2 < f g' e' c' >  |
                < a' c'' e'' > 2 < a g' b' d'' >  |
                < c'' a' f' g > 2 < f' a' c'' >  |
                < a' c'' e'' > 2 < a g' b' d'' >  |
                < g c'' a' f' > 2 < f c' e' g' >  |
%% 10
                < a' c'' e'' > 2 < d'' b' g' a >  |
                < g f' a' c'' > 2 < f' a' c'' >  |
                < a' c'' e'' > 2 < a d'' b' g' >  |
                < g f' a' c'' > 2 < f c' e' g' >  |
                < e'' c'' a' > 2 < a g' b' d'' >  |
%% 15
                < g f' a' c'' > 2 < f' a' c'' >  |
                < a' e'' c'' > 2 < a g' b' d'' >  |
                < g f' a' c'' > 2 < g' c' e' f >  |
                < c'' e'' a' > 2 < a g' b' d'' >  |
                < g f' a' c'' > 2 < a' c'' f' >  |
%% 20
                < f' a' c'' > 1  |
                < d' f' a' > 1  |
                < f' a' c'' > 1  |
                < b' e' g' > 1  |
                < f' a' c'' > 1  |
%% 25
                < d' f' a' > 1  |
                < f' a' c'' > 1  |
                < g' d'' b' > 1  |
                < a' c'' e'' > 2 < a g' b' d'' >  |
                < a' c'' g f' > 2 < f c' e' g' >  |
%% 30
                < a' c'' e'' > 2 < d'' b' g' a >  |
                < g f' a' c'' > 2 < f' a' c'' >  |
                < a' c'' e'' > 2 < b' d'' a g' >  |
                < g f' a' c'' > 2 < f c' e' g' >  |
                < e'' c'' a' > 2 < a g' b' d'' >  |
%% 35
                < g f' a' c'' > 2 < f' a' c'' >  |
                R1  |
                < g' c' e' > 1  |
                < g' b' d'' > 1  |
                < a' cis'' e'' > 1  |
%% 40
                < a' cis'' e'' > 1  |
                < e' g' c' > 1  |
                < g' b' d'' > 1  |
                < a' cis'' e'' > 1  |
                < a' cis'' e'' > 1  |
%% 45
                < g' e' c' > 1  |
                < b' d'' g' > 1  |
                < a' cis'' e'' > 1  |
                < a' cis'' e'' > 1  |
                < c' e' g' > 1  |
%% 50
                < g' d'' b' > 1  |
                < a' cis'' e'' > 1  |
                < a' cis'' e'' > 1  |
                < f' a' c'' > 1  |
                < a' d' f' > 1  |
%% 55
                < f' a' c'' > 1  |
                < e' g' b' > 1  |
                < f' a' c'' > 1  |
                < a' f' d' > 1  |
                < f' a' c'' > 1  |
%% 60
                < g' b' d'' > 1  |
                < a' c'' e'' > 2 < b' d'' a g' >  |
                < g f' a' c'' > 2 < f c' e' g' >  |
                < e'' c'' a' > 2 < a g' b' d'' >  |
                < g f' a' c'' > 2 < f' a' c'' >  |
%% 65
                < e'' a' c'' > 2 < a g' b' d'' >  |
                < g f' a' c'' > 2 < g' e' c' f >  |
                < a' c'' e'' > 2 < a g' b' d'' >  |
                < g f' a' c'' > 2 < c'' a' f' >  |
                R1  |
%% 70
                < c' e' g' > 1  |
                < g' b' d'' > 1  |
                < a' cis'' e'' > 1  |
                < e'' cis'' a' > 1  |
                < c' e' g' > 1  |
%% 75
                < g' b' d'' > 1  |
                < a' cis'' e'' > 1  |
                < cis'' e'' a' > 1  |
                < c' e' g' > 1  |
                < g' b' d'' > 1  |
%% 80
                < a' cis'' e'' > 1  |
                < cis'' e'' a' > 1  |
                < c' e' g' > 1  |
                < g' b' d'' > 1  |
                < a' cis'' e'' > 1  |
%% 85
                < e'' a' cis'' > 1  |
                < c' e' g' > 1  |
                < g' b' d'' > 1  |
                < a' cis'' e'' > 1  |
                < e'' cis'' a' > 1  |
%% 90
                < c' e' g' > 1  |
                < g' b' d'' > 1  |
                < a' cis'' e'' > 1  |
                < a' cis'' e'' > 1  |
            } % Voice
        >> % Staff (final) ends

    >> % notes

    \layout {
        \context { \GrandStaff \accepts "ChordNames" }
        \context { \GrandStaff \accepts "Lyrics" }
    }
%     uncomment to enable generating midi file from the lilypond source
%         \midi {
%         } 
} % score
