% This LilyPond file was generated by Rosegarden 11.06
\include "nederlands.ly"
\version "2.12.0"
\header {
    copyright = "Copyright (c) 2011 Zajaro"
    subtitle = "patupan"
    title = "Jamiroquak"
    tagline = "Created using Rosegarden 11.06 and LilyPond"
}
\paper {
    ragged-bottom=##t
}
#(set-global-staff-size 26)
#(set-default-paper-size "a4" 'landscape)
global = { 
    \time 4/4
}
globalTempo = {
    \tempo 4 = 150
}
\score {
<< % common
        \override Score.NoteColumn #'force-hshift = #1.0

        \context Staff = "track 1" << 
            \set Staff.instrumentName = \markup { \column { " " } }
            \set Staff.midiInstrument = "Electric Piano 1"
            \set Staff.printKeyCancellation = ##f
            \new Voice \global
            \new Voice \globalTempo

            \context Voice = "voice 1" {
                \override Voice.TextScript #'padding = #2.0

                \clef "treble"
		r 2 r 4 .  . d 16 ~ |
                < g, d > 8 ~ < g, d b f' > 8 ~ < g, d b f' > 4 ~ < g, d b f' > 4  r 8 . a , 16 ~ |
                < d, a, > 8 ~ < d, a, fis c' > 8 ~ < d, a, fis c' > 4 ~ < d, a, fis c' > 4   r 8 .  e 16 ~ |
                < a, e > 8 ~ < a, e g' cis' > 8 ~ < a, e g' cis' > 4 ~ < a, e g' cis' > 4 r 4  |
                b, 8 ~ < b, e, d' aes > 4 . a, 8 ~  < a, d, fis c' > 4 r 16 d 16 ~ |
                < g, d > 8 ~ < g, d b f' > 8 ~ < g, d b f' > 4 ~ < g, d b f' > 4  r 8 . a , 16 ~ |
                < d, a, > 8 ~ < d, a, fis c' > 8 ~ < d, a, fis c' > 4 ~ < d, a, fis c' > 4   r 8 .  e 16 ~ |
                < a, e > 8 ~ < a, e g' cis' > 8 ~ < a, e g' cis' > 4 ~ < a, e g' cis' > 4 r 4  |
                b, 8 ~ < b, e, d' aes > 4 . a, 8 ~  < a, d, fis c' > 4 r 16 d 16 ~ |
                < g, d > 8 ~ < g, d b f' > 8 ~ < g, d b f' > 4 ~ < g, d b f' > 4  r 8 . a , 16 ~ |
                < d, a, > 8 ~ < d, a, fis c' > 8 ~ < d, a, fis c' > 4 ~ < d, a, fis c' > 4   r 8 .  e 16 ~ |
                < a, e > 8 ~ < a, e g' cis' > 8 ~ < a, e g' cis' > 4 ~ < a, e g' cis' > 4 r 4  |
                b, 8 ~ < b, e, d' aes > 4 . a, 8 ~  < a, d, fis c' > 4 r 16 d 16 ~ |
                < g, d > 8 ~ < g, d b f' > 8 ~ < g, d b f' > 4 ~ < g, d b f' > 4  r 8 . a , 16 ~ |
                < d, a, > 8 ~ < d, a, fis c' > 8 ~ < d, a, fis c' > 4 ~ < d, a, fis c' > 4   r 8 .  e 16 ~ |
                < a, e > 8 ~ < a, e g' cis' > 8 ~ < a, e g' cis' > 4 ~ < a, e g' cis' > 4 r 4  |
                b, 8 ~ < b, e, d' aes > 4 . a, 8 ~  < a, d, fis c' > 4 r 16 d 16 ~ |
                < g, d > 8 ~ < g, d b f' > 8 ~ < g, d b f' > 4 ~ < g, d b f' > 4  r 8 . a , 16 ~ |
                < d, a, > 8 ~ < d, a, fis c' > 8 ~ < d, a, fis c' > 4 ~ < d, a, fis c' > 4   r 8 .  e 16 ~ |
                < a, e > 8 ~ < a, e g' cis' > 8 ~ < a, e g' cis' > 4 ~ < a, e g' cis' > 4 r 4  |
                b, 8 ~ < b, e, d' aes > 4 . a, 8 ~  < a, d, fis c' > 4 r 16 d 16 ~ |
                < g, d > 8 ~ < g, d b f' > 8 ~ < g, d b f' > 4 ~ < g, d b f' > 4  r 8 . a , 16 ~ |
                < d, a, > 8 ~ < d, a, fis c' > 8 ~ < d, a, fis c' > 4 ~ < d, a, fis c' > 4   r 8 .  e 16 ~ |
                < a, e > 8 ~ < a, e g' cis' > 8 ~ < a, e g' cis' > 4 ~ < a, e g' cis' > 4 r 4  |
                b, 8 ~ < b, e, d' aes > 4 . a, 8 ~  < a, d, fis c' > 4 r 16 d 16 ~ |
                \bar "|."
            } % Voice
        >> % Staff ends

        \context Staff = "track 2" << 
            \set Staff.instrumentName = \markup { \column { " " } }
            \set Staff.midiInstrument = "fretless bass"
            \set Staff.printKeyCancellation = ##f
            \new Voice \global
            \new Voice \globalTempo

            \context Voice = "voice 7" {
                \override Voice.TextScript #'padding = #2.0
                \override MultiMeasureRest #'expand-limit = 1

                \clef "bass"
                \skip 1*5 
		g,, 16 g,, 16 r8 r16 d,16 d,16 r16 g,,8 d,8 g,,8 c,8 | 
		d, 16 d, 16 r8 r16 a,16 a,16 r16 d,8 a,8 d,8 c,8 | 
		a,, 16 a,, 16 r8 r16 e,16 e,16 r16 a,,8 e,8 a,,8 d,8 | 
		e, 16 e, 16 r8 r16 b,16 b,16 r16 d,8 a,8 d,8 a,,8 | 
		g,, 16 g,, 16 r8 r16 d,16 d,16 r16 g,,8 d,8 g,,8 c,8 | 
		d, 16 d, 16 r8 r16 a,16 a,16 r16 d,8 a,8 d,8 c,8 | 
		a,, 16 a,, 16 r8 r16 e,16 e,16 r16 a,,8 e,8 a,,8 d,8 | 
		e, 16 e, 16 r8 r16 b,16 b,16 r16 d,8 a,8 d,8 a,,8 | 
		g,, 16 g,, 16 r8 r16 d,16 d,16 r16 g,,8 d,8 g,,8 c,8 | 
		d, 16 d, 16 r8 r16 a,16 a,16 r16 d,8 a,8 d,8 c,8 | 
		a,, 16 a,, 16 r8 r16 e,16 e,16 r16 a,,8 e,8 a,,8 d,8 | 
		e, 16 e, 16 r8 r16 b,16 b,16 r16 d,8 a,8 d,8 a,,8 | 
		g,, 16 g,, 16 r8 r16 d,16 d,16 r16 g,,8 d,8 g,,8 c,8 | 
		d, 16 d, 16 r8 r16 a,16 a,16 r16 d,8 a,8 d,8 c,8 | 
		a,, 16 a,, 16 r8 r16 e,16 e,16 r16 a,,8 e,8 a,,8 d,8 | 
		e, 16 e, 16 r8 r16 b,16 b,16 r16 d,8 a,8 d,8 a,,8 | 
		g,, 16 g,, 16 r8 r16 d,16 d,16 r16 g,,8 d,8 g,,8 c,8 | 
		d, 16 d, 16 r8 r16 a,16 a,16 r16 d,8 a,8 d,8 c,8 | 
		a,, 16 a,, 16 r8 r16 e,16 e,16 r16 a,,8 e,8 a,,8 d,8 | 
		e, 16 e, 16 r8 r16 b,16 b,16 r16 d,8 a,8 d,8 a,,8 | 
                \bar "|."
            } % Voice
        >> % Staff ends

        \context DrumStaff = "track 3" << 
            \set DrumStaff.instrumentName = \markup { \column { " " } }
            \set DrumStaff.printKeyCancellation = ##f
            \new DrumVoice \global
            \new DrumVoice \globalTempo

            \context DrumVoice = "voice 12" {
                \override DrumVoice.TextScript #'padding = #2.0

                \drummode {
                hhc 2 hhc 2 |
                hhc 2 hhc 2 |
                hhc 2 hhc 2 |
                hhc 2 hhc 2 | 
                hhc 2 hhc 2 |
                hhc 2 hhc 2 |
                hhc 2 hhc 2 |
                hhc 2 hhc 2 |
                hhc 2 hhc 2 |
                < hhc bd > 2 < hhc bd > 2 |
                < hhc bd > 2 < hhc bd > 2 |
                < hhc bd > 2 < hhc bd > 2 |
                < hhc bd > 2 < hhc bd > 2 |
                < hhc bd > 2 < hhc bd > 2 |
                < hhc bd > 2 < hhc bd > 2 |
                < hhc bd > 2 < hhc bd > 2 |
                < hhc bd > 2 < hhc bd > 2 |
                < hhc bd > 4 < hhc sn > 8  bd8  hhc 8 bd 8 < hhc sn > 4 |
                < hhc bd > 4 < hhc sn > 8  bd8  hhc 8 bd 8 < hhc sn > 4 |
                < hhc bd > 4 < hhc sn > 8  bd8  hhc 8 bd 8 < hhc sn > 4 |
                < hhc bd > 4 < hhc sn > 8  bd8  hhc 8 bd 8 < hhc sn > 4 |
                < hhc bd > 4 < hhc sn > 8  bd8  hhc 8 bd 8 < hhc sn > 4 |
                < hhc bd > 4 < hhc sn > 8  bd8  hhc 8 bd 8 < hhc sn > 4 |
                < hhc bd > 4 < hhc sn > 8  bd8  hhc 8 bd 8 < hhc sn > 4 |
                < hhc bd > 4 < hhc sn > 8  bd8  hhc 8 bd 8 < hhc sn > 4 |
                \bar "|." }
            } % Voice
        >> % Staff (final) ends

    >> % notes

    \layout {
    }
%     uncomment to enable generating midi file from the lilypond source
         \midi {
         } 
} % score
