% This LilyPond file was generated by Rosegarden 11.06
\include "nederlands.ly"
\version "2.12.0"
\header {
    copyright = "Copyright (c) 2004 Zajaro"
    subtitle = "not yet subtitled"
    title = "Jarreando"
    tagline = "Created using Rosegarden 11.06 and LilyPond"
}
#(set-global-staff-size 16)
#(set-default-paper-size "a4")
global = { 
    \time 4/4

}
globalTempo = {
    \tempo 4 = 120
}
markers = {
}
silenceA = {
  r1 |
  r1 |
  r1 |
  r1 |
}
silenceB ={
  r1 |
  r1 |
  r1 |
}
silenceC ={
  r1 |
  r1 |
}
motifA = {
  r8 f'8 f'8 c''8~c''8 f'8 f'8 a'8~ |
  a'8 f'8 f'8 f'8~ f'8 f''8~f''4 |
}
motifAA = {
  f''8 f'8 f'8 c''8~c''8 f'8 f'8 a'8~ |
  a'8 f'8 f'8 f'8~ f'8 f''8~f''4 |
}
lidA = {
  \silenceA
  \silenceB
  a1~ |
  a1~ |
  a1 |
  g1~ |
  g1~ |
  g1~ |
  g4. c'8~c'2 |
  c'1~ |
  c'1~ |
  c'2~c'4~c'8 a8~ |
  a1~ |
  a1~ |
  a1~ |
  a1~ |
  a1 |
  g1~ |
  g1~ |
  g1 |
  d'1~ |
  d'1 |
  a1~ |
  a1 |
  g1 |
  a1 |
  b1 |
  c1~ |
  c1 |
  \motifA
  \motifAA
  f''1 |
  g''1~ |
  g''1~ |
  g''1 |
  \motifA
  \motifAA
  f''1 |
  g''1~ |
  g''1~ |
  g''1 |
  \motifA
  \motifAA
  f''1 |
  g''1~ |
  g''1~ |
  g''1 |
  \motifA
  \motifAA
  f''1 |
  g''1~ |
  g''1~ |
  g''1 |
}
lidB = {
  \times 2/3 { b4 c'4 a4 d'4. e'4.~} |
  \times 2/3 {e'4.~ e'4 g'8~g'2. }|
  \times 2/3 {b4 c'4 a4 g4.~ g4.~ }|
  \times 2/3 {g4. d'4.~ d'2. }|
  \times 2/3 {f'4.~f'4 b'8~b'2. }|
  \times 2/3 {b4 c'4 a4 d'4. e'4.~ }|
  \times 2/3 {e'4.~ e'4 g'8~g'2. }|
  \times 2/3 {b4 c'4 a4 g4.~ g4.~ }|
  \times 2/3 {g4.~g4 d'8~ d'2. }|
  \times 2/3 {f'4.~f'4 b'8~b'2. }|
  \times 2/3 {b4 c'4 a4 d'4. e'4.~ }|
  \times 2/3 {e'4.~ e'4 g'8~g'2.~ }|
  g'1 |
}
lidC = {
  r8 f'8 f'8 c''4 f'8 f'8 a'8~ |
  a'8 f'8 f'8 f'8~ f'8 f''8~f''4 |
  f''8 f'8 f'8 c''8~c''8 f'8 f'8 a'8~ |
  a'8 f'8 f'8 f'8~ f'8 f''8~f''4 |
  f''1 |
  g''1~ |
  g''1~ |
  g''1 |
  r8 f'8 f'8 c''8~c''8 f'8 f'8 a'8~ |
  a'8 f'8 f'8 f'8~ f'8 f''4. |
  f''8 f'8 f'8 c''8~c''8 f'8 f'8 a'8~ |
  a'8 f'8 f'8 f'8~ f'8 f''8~f''4 |
  f''1 |
  g''1~ |
  g''1~ |
  g''1 |
}
lid = {
 \lidA
r1 |
 \lidB

\lidC

  \bar "|."
}
guokinA = {
  % 1
  r1 |
  r4. f 8 e8 g8 g8 c'8~ |
  c'2 g8 a8 c'8 a8  |
  g 8 g 4 c'8~c'8 g' 4.~ |
  %
  g'1 |
  r4. f 8 e8 g8 g8 c'8~ |
  c'2 g8 a8 c'8 a8  |
  g 8 g 4 c'8~c'8 a' 4.~ |
  % 
  a'1 |
  r4. f 8 e8 g8 g8 c'8~ |
  c'2 g8 a8 c'8 a8  |
  g 8 g 4 c'8~c'8 f' 4.~ |
  % 
  f'1 |
  r4. f 8 e8 g8 g8 c'8~ |
  c'2 g8 a8 c'8 a8  |
  g 8 g 4 c'8~c'8 e' 4.~ |
  % 17
  e'1 |
  r4. f 8 e8 g8 g8 c'8~ |
  c'2 g8 a8 c'8 a8  |
  g 8 g 4 c'8~c'8 g' 4.~ |
  %
  g'1 |
  r4. f 8 e8 g8 g8 c'8~ |
  c'2 g8 a8 c'8 a8  |
  g 8 g 4 c'8~c'8 a' 4.~ |
  %
  a'1 |
  r4. f 8 e8 g8 g8 c'8~ |
  c'2 g8 a8 c'8 a8  |
  %
  g 8 g 4 c'8~c'8 f' 4.~ |
  f'1 |
  r4. f 8 e8 g8 g8 c'8~ |
  c'2 g8 a8 c'8 a8  |
  % 33
  g 8 g 4 c'8~c'8 e' 4.~ |
  e'1 |
  r1 |
  r8 f8 f8 c'8~c'8 f8 f8 a8~ |
  a8 f8 f8 f8~ f8 f'4. |
  f'8 f8 f8 c'4 f8 f8 f'8~ |
  f'1 |
  g'1 |
  \silenceB
  r8 f8 f8 c'8~c'8 f8 f8 a8~ |
  a8 f8 f8 f8~ f8 f'4. |
  f'8 f8 f8 c'4 f8 f8 f'8~ |
  f'1 |
  g'1 |
  \silenceB
  r8 f8 f8 c'8~c'8 f8 f8 a8~ |
  a8 f8 f8 f8~ f8 f'4. |
  f'8 f8 f8 c'4 f8 f8 f'8~ |
  f'1 |
  g'1 |
  \silenceB
  r8 f8 f8 c'8~c'8 f8 f8 a8~ |
  a8 f8 f8 f8~ f8 f'4. |
  f'8 f8 f8 c'4 f8 f8 f'8~ |
  f'1 |
  g'1 |
  \silenceA
}
guokinB = {
  \silenceA
  \silenceA
  \silenceA
}
guokinC = {
  r8 f8 f8 c'8~c'8 f8 f8 a8~ |
  a8 f8 f8 f8~ f4 f'4 |
  f'8 f8 f8 c'4 f8 f8 f'8~ |
  f'1 |
  g'1 |
  \silenceB
  r8 f8 f8 c'8~c'8 f8 f8 a8~ |
  a8 f8 f8 f8~ f8 f'4. |
  f'8 f8 f8 c'4 f8 f8 f'8~ |
  f'1 |
}
guokin = {
  \guokinA

  \guokinB
  r1 |
  \guokinC
  \silenceA
  \bar "|."
}
chapasA = {
  < c' e' g' >4. < f' a' c'' >8~ < f' a' c'' >4  < g' b' d'' >4 |
  < f' a' c'' >2~ < f' a' c'' >8 < g' b' d'' >4 < g' b' d'' >8 |
  < c' e' g' >4 < c' e' g' >8 < f' a' c'' >8~ < f' a' c'' >4 < g' b' d'' >8 < g' b' d'' >8~ |
  < g' b' d'' >8 < f' a' c'' >8~ < f' a' c'' >4 < f' a' c'' >2 |
}
chapasB ={
  < f a c' >1~ |
  < f a c' >1~ |
  < f a c' >1~ |
  < f a c' >1~ |
  < f a c' >1 |
}
chapasC = {
  \times 2/3 { < g, b, d g >4 < b d' g' b' >4 < g, b, d g >4 } < b d' g' b' >4 < g, b, d g >4  |
  < g, d b g' >4 < b, g d' b' >4 < g, d b g' >4 < b, g d' b' >4 |

  }
chapas = {
  \chapasA
  \chapasA
  \chapasA
  \chapasA
  \chapasA
  \chapasA
  \chapasA
  \chapasA
  \silenceC
  \chapasB
  \silenceB
  \chapasB
  \silenceB
  \chapasB
  \silenceB
  \chapasB
  \silenceB
  \silenceC
  \chapasC
  \chapasC
  \chapasC
  \chapasC
  \chapasC
  \chapasC
  \chapasB
  \silenceB
  \chapasB
  \silenceB
  \bar "|."
}

bajobaseA = {
  c,4 c,4 c,4 c,4  |
  c,4 c,4 c,4 c,4  |
  c,4 c,4 c,4 c,4  |
  c,4 c,4 c,4 c,4  |
}

bajo = {
  \bajobaseA
  \bajobaseA
  \bajobaseA
  \bajobaseA
  \bajobaseA
  \bajobaseA
  \bajobaseA
  \bajobaseA
  \bajobaseA
  \bajobaseA
  \bajobaseA
  \bajobaseA
  \bajobaseA
  \bajobaseA
  \bajobaseA
  \bajobaseA
  \bajobaseA
  \bajobaseA
  \bajobaseA
  \silenceB
  \silenceA
  \silenceA
  \silenceA
  \silenceC
  \silenceB
  \bar "|."
}

bataintro = \drummode {
  hhp8 ss8 hhp8 ss8 hhp8 ss8 hhp4 |
  <bd hhp>8 ss8 hhp8 ss8 <bd hhp>8 ss8 hhp4 |
}
bataA ={
}
bataB = {
}
bataC = {
}

\bateria = {
  \bataintro
  \bataA
  \bataB
  \bataC
}


\score {
<< % common
        % force offset of colliding notes in chords:
        \override Score.NoteColumn #'force-hshift = #1.0
        \context Staff = "lid" << 
            \set Staff.instrumentName = \markup { \column { "lid" } }
            \set Staff.midiInstrument = "Lead 1 (square)"
            \set Score.skipBars = ##t
            \set Staff.printKeyCancellation = ##f
            \new Voice \global
            \new Voice \globalTempo
            \new Voice \markers

            \context Voice = "lid" {
                \override Voice.TextScript #'padding = #2.0
                \override MultiMeasureRest #'expand-limit = 1

                \once \override Staff.TimeSignature #'style = #'() \time 4/4
                \clef "treble_8"
                \key c \major
                \lid
            } % Voice
        >> % Staff (final) ends
        

        \context Staff = "guokin" << 
            \set Staff.instrumentName = \markup { \column { "guokin" } }
            \set Staff.midiInstrument = "Lead 2 (sawtooth)"
            \set Score.skipBars = ##t
            \set Staff.printKeyCancellation = ##f
            \new Voice \global
            \new Voice \globalTempo
            \new Voice \markers

            \context Voice = "guokin" {
                \override Voice.TextScript #'padding = #2.0
                \override MultiMeasureRest #'expand-limit = 1

                \once \override Staff.TimeSignature #'style = #'() \time 4/4
                \clef "treble_8"
                \key c \major
                \guokin
            } % Voice
        >> % Staff ends

        \context Staff = "chapas" << 
            \set Staff.instrumentName = \markup { \column { "chapas" } }
            \set Staff.midiInstrument = "Pad 3 (polysynth)"
            \set Score.skipBars = ##t
            \set Staff.printKeyCancellation = ##f
            \new Voice \global
            \new Voice \globalTempo
            \new Voice \markers

            \context Voice = "chapas" {
                \override Voice.TextScript #'padding = #2.0
                \override MultiMeasureRest #'expand-limit = 1

                \once \override Staff.TimeSignature #'style = #'() \time 4/4
                \clef "treble"
                \key c \major
                \chapas
            } % Voice
        >> % Staff ends
\context Staff = "bajo" << 
            \set Staff.instrumentName = \markup { \column { "bajo" } }
            \set Staff.midiInstrument = "acoustic bass"
            \set Score.skipBars = ##t
            \set Staff.printKeyCancellation = ##f
            \new Voice \global
            \new Voice \globalTempo
            \new Voice \markers

            \context Voice = "bajo" {
                \override Voice.TextScript #'padding = #2.0
                \override MultiMeasureRest #'expand-limit = 1

                \once \override Staff.TimeSignature #'style = #'() \time 4/4
                \clef "bass_8"
                \key c \major
               \bajo
            } % Voice
        >> % Staff ends
        %\context Staff = "Bateria" << 
        %   \set Staff.instrumentName = \markup { \column { "bateria" } }
        %    %\set Staff.midiInstrument = ""
        %   \set Score.skipBars = ##t
        %   \set Staff.printKeyCancellation = ##f
        %   \new Voice \global
        %   \new Voice \globalTempo
        %   \new Voice \markers
        %
        %   \context Voice = "bateria" {
        %       \override Voice.TextScript #'padding = #2.0
        %       \override MultiMeasureRest #'expand-limit = 1
        %
        %       \once \override Staff.TimeSignature #'style = #'() \time 4/4
        %       \clef "percussion"
        %       \bateria
        %   } % Voice
        %>> % Staff ends



    >> % notes

    \layout {
        \context { \GrandStaff \accepts "ChordNames" }
        \context { \GrandStaff \accepts "Lyrics" }
    }
%     uncomment to enable generating midi file from the lilypond source
         \midi {
         } 
} % score
