% This LilyPond file was generated by Rosegarden 11.11.42
\include "nederlands.ly"
\version "2.12.0"
\header {
    copyright = "Copyright (c) xxxx Copyright Holder"
    subtitle = "not yet subtitled"
    title = "Not Yet Titled"
    tagline = "Created using Rosegarden 11.11.42 and LilyPond"
}
#(set-global-staff-size 26)
#(set-default-paper-size "a4")
global = { 
    \time 4/4
    \skip 1*91 
}
globalTempo = {
    \tempo 4 = 135  
}
\score {
<< % common
        % force offset of colliding notes in chords:
        \override Score.NoteColumn #'force-hshift = #1.0

        \context Staff = "track 1, guitarra" << 
            \set Staff.instrumentName = \markup { \column { "guitarra " } }
            \set Staff.midiInstrument = ""
            \set Score.skipBars = ##t
            \set Staff.printKeyCancellation = ##f
            \new Voice \global
            \new Voice \globalTempo

            \context Voice = "voice 1" {
                \override Voice.TextScript #'padding = #2.0
                \override MultiMeasureRest #'expand-limit = 1

                \skip 1*18 
%% 20
                \clef "treble"
                \key dis \minor
                < gis' fisis'' dis'' bis' > 1  |
                < ais' fisis' e' bis > 1  |
                < ais' dis' cisis' b > 1  |
                < eis'' cisis'' ais' fisis' > 1  |
                < dis'' b' gis' e' > 1  |
%% 25
                < bis' gis' eis' cis' > 1  |
                < eis'' dis'' b' gis' > 1  |
                < fisis'' dis'' gis' bis' > 1  |
                < fisis'' dis'' bis' gis' > 1  |
                < ais' fisis' e' bis > 1  |
%% 30
                < ais' dis' cisis' b > 1  |
                < eis'' cisis'' ais' fisis' > 1  |
                < dis'' b' gis' e' > 1  |
                < bis' gis' eis' cis' > 1  |
                < eis'' dis'' b' gis' > 1  |
%% 35
                < fisis'' dis'' gis' bis' > 1  |
                R1*41  |
                < fisis'' dis'' bis' gis' > 1  |
                < ais' fisis' e' bis > 1  |
                < ais' dis' cisis' b > 1  |
%% 80
                < eis'' cisis'' ais' fisis' > 1  |
                < dis'' b' gis' e' > 1  |
                < bis' gis' eis' cis' > 1  |
                < eis'' dis'' b' gis' > 1  |
                < fisis'' dis'' gis' bis' > 1  |
%% 85
                < fisis'' dis'' bis' gis' > 1  |
                < ais' fisis' e' bis > 1  |
                < ais' dis' cisis' b > 1  |
                < eis'' cisis'' ais' fisis' > 1  |
                < dis'' b' gis' e' > 1  |
%% 90
                < bis' gis' eis' cis' > 1  |
                < eis'' dis'' b' gis' > 1  |
                < fisis'' dis'' gis' bis' > 2..  |
            } % Voice
        >> % Staff ends

        \context Staff = "track 2, paloL" << 
            \set Staff.instrumentName = \markup { \column { "paloL " } }
            \set Staff.midiInstrument = ""
            \set Score.skipBars = ##t
            \set Staff.printKeyCancellation = ##f
            \new Voice \global
            \new Voice \globalTempo

            \context Voice = "voice 2" {
                \override Voice.TextScript #'padding = #2.0
                \override MultiMeasureRest #'expand-limit = 1

                \skip 1*18 
%% 20
                \clef "tenor"
                \key dis \minor
                < dis gis > 1  |
                < bis fisis > 2. r4  |
                < dis' ais > 2. r4  |
                < fisis cisis > 1  |
                < b e > 2. r4  |
%% 25
                < cis' gis > 2. r4  |
                < eis' b > 2. r4  |
                < gis dis > 2. r4  |
                < gis dis > 1  |
                < bis fisis > 2. r4  |
%% 30
                < dis' ais > 2. r4  |
                < fisis cisis > 1  |
                < b e > 2. r4  |
                < cis' gis > 2. r4  |
                < eis' b > 2. r4  |
%% 35
                < gis dis > 2. r4  |
                R1  |
                < gis dis > 2 -\tenuto r4 < bis fisis >  |
                < dis' ais > 2 -\tenuto r4 < fisis cisis >  |
                < gis dis > 1  |
%% 40
                < fisis cisis > 1  |
                < gis dis > 2 -\tenuto r4 < bis fisis >  |
                < dis' ais > 2 -\tenuto r4 < fisis cisis >  |
                < gis dis > 1  |
                < fisis cisis > 1  |
%% 45
                < gis dis > 2 -\tenuto r4 < bis fisis >  |
                < dis' ais > 2 -\tenuto r4 < fisis cisis >  |
                < gis dis > 1  |
                < fisis cisis > 1  |
                < gis dis > 2 -\tenuto r4 < bis fisis >  |
%% 50
                < dis' ais > 2 -\tenuto r4 < fisis cisis >  |
                < gis dis > 1  |
                < fisis cisis > 1  |
                < gis, dis, > 8. r16 r8 < b, e, > 4 -\tenuto r8 r < bis, fisis, > -\tenuto 
                % warning: overlong bar truncated here |
                \skip 8 r8 r4 r2  |
%% 55
                < bis, fisis, > 8. r16 r8 < cis gis, > 4 -\tenuto r8 r < e ais, > -\tenuto 
                % warning: overlong bar truncated here |
                \skip 8 r8 r4 r2  |
                < dis ais, > 8. r16 r8 < eis b, > 4 -\tenuto r8 r < fis cisis > -\tenuto 
                % warning: overlong bar truncated here |
                \skip 8 r8 r4 r2  |
                < fisis cisis > 8. r16 r8 < gis dis > 4 -\tenuto r8 r < ais e > -\tenuto 
                % warning: overlong bar truncated here |
%% 60
                \skip 8 r8 r4 r2  |
                R1*16  |
                < gis dis > 1  |
                < bis fisis > 2. r4  |
                < dis' ais > 2. r4  |
%% 80
                < fisis cisis > 1  |
                < b e > 2. r4  |
                < cis' gis > 2. r4  |
                < eis' b > 2. r4  |
                < gis dis > 2. r4  |
%% 85
                < gis dis > 1  |
                < bis fisis > 2. r4  |
                < dis' ais > 2. r4  |
                < fisis cisis > 1  |
                < b e > 2. r4  |
%% 90
                < cis' gis > 2. r4  |
                < eis' b > 2. r4  |
                < gis dis > 2 -\tenuto r8 r16  |
            } % Voice
        >> % Staff ends

        \context Staff = "track 3, bajo" << 
            \set Staff.instrumentName = \markup { \column { "bajo " } }
            \set Staff.midiInstrument = ""
            \set Score.skipBars = ##t
            \set Staff.printKeyCancellation = ##f
            \new Voice \global
            \new Voice \globalTempo

            \context Voice = "voice 3" {
                \override Voice.TextScript #'padding = #2.0
                \override MultiMeasureRest #'expand-limit = 1

                \skip 1*5 
                \clef "bass_15"
                \key dis \minor
                ais,, 8 r16 ais,, 8 r16 eis, 4 r8 eis, 4  |
                ais,, 8 r16 eis, 8 r16 ais,, 4 r8 eis, 4  |
                dis, 8 r16 ais, 8 r16 dis, 4 r8 ais, 4  |
%% 10
                dis, 8 r16 dis, 8 r16 ais, 4 r8 ais, 4  |
                ais,, 8 r16 ais,, 8 r16 eis, 4 r8 eis, 4  |
                ais,, 8 r16 eis, 8 r16 ais,, 4 r8 eis, 4  |
                dis, 8 r16 ais, 8 r16 dis, 4 r8 ais, 4  |
                dis, 8 r16 dis, 8 r16 ais, 4 r8 ais, 4  |
%% 15
                ais,, 8 r16 ais,, 8 r16 eis, 4 r8 eis, 4  |
                ais,, 8 r16 eis, 8 r16 ais,, 4 r8 eis, 4  |
                dis, 8 r16 ais, 8 r16 dis, 4 r8 ais, 4  |
                dis, 8 r16 dis, 8 r16 ais, 4 r8 ais, 4  |
                R1  |
%% 20
                gis, 8. r16 r8 fis, r gis, r b,,  |
                bis,, 8. r16 r8 ais,, r bis,, r bis,,  |
                b,, 8. r16 r8 ais,, r b,, r fis,  |
                fisis, 8. r16 r8 eis, r fisis, r dis,  |
                e, 8. r16 r8 cisis, r e, r cisis,  |
%% 25
                cis, 8. r16 r8 b,, r cis, r fisis,  |
                gis, 8. r16 r8 fis, r gis, r a,  |
                gis, 8. r16 r8 fis, r gis, r fisis,  |
                gis, 8. r16 r8 fis, r gis, r b,,  |
                bis,, 8. r16 r8 ais,, r bis,, r bis,,  |
%% 30
                b,, 8. r16 r8 ais,, r b,, r fis,  |
                fisis, 8. r16 r8 eis, r fisis, r dis,  |
                e, 8. r16 r8 cisis, r e, r cisis,  |
                cis, 8. r16 r8 b,, r cis, r fisis,  |
                gis, 8. r16 r8 fis, r gis, r a,  |
%% 35
                gis, 8. r16 r8 fis, r gis, r fisis,  |
                R1  |
                gis,, 16 gis,, r gis,, dis, 8. r16 gis,, gis,, r gis,, bis,, r bis,, r  |
                b,, 16 b,, r b,, fis, 8. r16 b,, b,, r b,, fisis,, r fisis,, r  |
                gis,, 16 gis,, r gis,, dis, 8. r16 gis,, gis,, r gis,, eis,, 8 eis,,  |
%% 40
                fisis,, 16 fisis,, r fisis,, cisis, 8. r16 fisis,, fisis,, r fisis,, a,, 8 a,,  |
                gis,, 16 gis,, r gis,, dis, 8. r16 gis,, gis,, r gis,, bis,, r bis,, r  |
                b,, 16 b,, r b,, fis, 8. r16 b,, b,, r b,, fisis,, r fisis,, r  |
                gis,, 16 gis,, r gis,, dis, 8. r16 gis,, gis,, r gis,, eis,, 8 eis,,  |
                fisis,, 16 fisis,, r fisis,, cisis, 8. r16 fisis,, fisis,, r fisis,, a,, 8 a,,  |
%% 45
                gis,, 16 gis,, r gis,, dis, 8. r16 gis,, gis,, r gis,, bis,, r bis,, r  |
                b,, 16 b,, r b,, fis, 8. r16 b,, b,, r b,, fisis,, r fisis,, r  |
                gis,, 16 gis,, r gis,, dis, 8. r16 gis,, gis,, r gis,, eis,, 8 eis,,  |
                fisis,, 16 fisis,, r fisis,, cisis, 8. r16 fisis,, fisis,, r fisis,, a,, 8 a,,  |
                gis,, 16 gis,, r gis,, dis, 8. r16 gis,, gis,, r gis,, bis,, r bis,, r  |
%% 50
                b,, 16 b,, r b,, fis, 8. r16 b,, b,, r b,, fisis,, r fisis,, r  |
                gis,, 16 gis,, r gis,, dis, 8. r16 gis,, gis,, r gis,, eis,, 8 eis,,  |
                fisis,, 16 fisis,, r fisis,, cisis, 8. r16 fisis,, fisis,, r fisis,, a,, 8 a,,  |
                gis,, 8 r r bis,, r4 r8 dis,  |
                R1  |
%% 55
                bis,, 8 r r e, r4 r8 fisis,  |
                R1  |
                b,, 8 r r dis, r4 r8 fis,  |
                R1  |
                fisis,, 8 r r b,, r4 r8 cisis,  |
%% 60
                R1  |
                ais,, 8 r16 ais,, 8 r16 eis, 4 r8 eis, 4  |
                ais,, 8 r16 eis, 8 r16 ais,, 4 r8 eis, 4  |
                dis, 8 r16 ais, 8 r16 dis, 4 r8 ais, 4  |
                dis, 8 r16 dis, 8 r16 ais, 4 r8 ais, 4  |
%% 65
                ais,, 8 r16 ais,, 8 r16 eis, 4 r8 eis, 4  |
                ais,, 8 r16 eis, 8 r16 ais,, 4 r8 eis, 4  |
                dis, 8 r16 ais, 8 r16 dis, 4 r8 ais, 4  |
                dis, 8 r16 dis, 8 r16 ais, 4 r8 ais, 4  |
                ais,, 8 r16 ais,, 8 r16 eis, 4 r8 eis, 4  |
%% 70
                ais,, 8 r16 eis, 8 r16 ais,, 4 r8 eis, 4  |
                dis, 8 r16 ais, 8 r16 dis, 4 r8 ais, 4  |
                dis, 8 r16 dis, 8 r16 ais, 4 r8 ais, 4  |
                ais,, 8 r16 ais,, 8 r16 eis, 4 r8 eis, 4  |
                ais,, 8 r16 eis, 8 r16 ais,, 4 r8 eis, 4  |
%% 75
                dis, 8 r16 ais, 8 r16 dis, 4 r8 ais, 4  |
                dis, 8 r16 dis, 8 r16 ais, 4 r8 ais, 4  |
                gis, 8. r16 r8 fis, r gis, r b,,  |
                bis,, 8. r16 r8 ais,, r bis,, r bis,,  |
                b,, 8. r16 r8 ais,, r b,, r fis,  |
%% 80
                fisis, 8. r16 r8 eis, r fisis, r dis,  |
                e, 8. r16 r8 cisis, r e, r cisis,  |
                cis, 8. r16 r8 b,, r cis, r fisis,  |
                gis, 8. r16 r8 fis, r gis, r a,  |
                gis, 8. r16 r8 fis, r gis, r fisis,  |
%% 85
                gis, 8. r16 r8 fis, r gis, r b,,  |
                bis,, 8. r16 r8 ais,, r bis,, r bis,,  |
                b,, 8. r16 r8 ais,, r b,, r fis,  |
                fisis, 8. r16 r8 eis, r fisis, r dis,  |
                e, 8. r16 r8 cisis, r e, r cisis,  |
%% 90
                cis, 8. r16 r8 b,, r cis, r fisis,  |
                gis, 8. r16 r8 fis, r gis, r a,  |
                gis, 8. r16 r8 fis, r gis, r fisis,  |
                \bar "|."
            } % Voice
        >> % Staff ends

        \context Staff = "track 4, paloD" << 
            \set Staff.instrumentName = \markup { \column { "paloD " } }
            \set Staff.midiInstrument = ""
            \set Score.skipBars = ##t
            \set Staff.printKeyCancellation = ##f
            \new Voice \global
            \new Voice \globalTempo

            \context Voice = "voice 4" {
                \override Voice.TextScript #'padding = #2.0
                \override MultiMeasureRest #'expand-limit = 1

                \skip 1 
                \clef "treble"
                \key dis \minor
                < cis' a' eis' > 4 -\tenuto r8 < a' eis' cis' > 4 -\tenuto r8 < ais' eis' cis' > 8. r16  |
                < a' eis' cis' > 4 -\tenuto r8 < a' eis' cis' > 4 -\tenuto r8 < ais' eis' cis' > 4  |
%% 5
                < fisis' dis' ais > 4 -\tenuto r8 < fisis' dis' ais > 4 -\tenuto r8 < fisis' dis' ais > 4  |
                < fisis' dis' ais > 4 -\tenuto r8 < fisis' dis' ais > 4 -\tenuto r8 < fisis' dis' ais > 4  |
                < a' eis' cis' > 4 -\tenuto r8 < a' eis' cis' > 4 -\tenuto r8 < ais' eis' cis' > 8. r16  |
                < a' eis' cis' > 4 -\tenuto r8 < a' eis' cis' > 4 -\tenuto r8 < ais' eis' cis' > 4  |
                < fisis' dis' ais > 4 -\tenuto r8 < fisis' dis' ais > 4 -\tenuto r8 < fisis' dis' ais > 4  |
%% 10
                < fisis' dis' ais > 4 -\tenuto r8 < fisis' dis' ais > 4 -\tenuto r8 < fisis' dis' ais > 4  |
                < a' eis' cis' > 4 -\tenuto r8 < a' eis' cis' > 4 -\tenuto r8 < ais' eis' cis' > 8. r16  |
                < a' eis' cis' > 4 -\tenuto r8 < a' eis' cis' > 4 -\tenuto r8 < ais' eis' cis' > 4  |
                < fisis' dis' ais > 4 -\tenuto r8 < fisis' dis' ais > 4 -\tenuto r8 < fisis' dis' ais > 4  |
                < fisis' dis' ais > 4 -\tenuto r8 < fisis' dis' ais > 4 -\tenuto r8 < fisis' dis' ais > 4  |
%% 15
                < a' eis' cis' > 4 -\tenuto r8 < a' eis' cis' > 4 -\tenuto r8 < ais' eis' cis' > 8. r16  |
                < a' eis' cis' > 4 -\tenuto r8 < a' eis' cis' > 4 -\tenuto r8 < ais' eis' cis' > 4  |
                < fisis' dis' ais > 4 -\tenuto r8 < fisis' dis' ais > 4 -\tenuto r8 < fisis' dis' ais > 4  |
                < fisis' dis' ais > 4 -\tenuto r8 < fisis' dis' ais > 4 -\tenuto r8 < fisis' dis' ais > 4  |
                R1  |
%% 20
                < bis' fisis' > 1  |
                < e'' ais' > 2. r4  |
                < fis'' cisis'' > 2. r4  |
                < ais' eis' > 1  |
                < dis'' gis' > 2. r4  |
%% 25
                < eis'' bis' > 2. r4  |
                < gis'' dis'' > 2. r4  |
                < bis' fisis' > 2. r4  |
                < bis' fisis' > 1  |
                < e'' ais' > 2. r4  |
%% 30
                < fis'' cisis'' > 2. r4  |
                < ais' eis' > 1  |
                < dis'' gis' > 2. r4  |
                < eis'' bis' > 2. r4  |
                < gis'' dis'' > 2. r4  |
%% 35
                < bis' fisis' > 2. r4  |
                R1  |
                < bis' fisis' > 2 -\tenuto r4 < e'' ais' >  |
                < fis'' cisis'' > 2 -\tenuto r4 < ais' eis' >  |
                < bis' fisis' > 1  |
%% 40
                < ais' eis' > 1  |
                < bis' fisis' > 2 -\tenuto r4 < e'' ais' >  |
                < fis'' cisis'' > 2 -\tenuto r4 < ais' eis' >  |
                < bis' fisis' > 1  |
                < ais' eis' > 1  |
%% 45
                < bis' fisis' > 2 -\tenuto r4 < e'' ais' >  |
                < fis'' cisis'' > 2 -\tenuto r4 < ais' eis' >  |
                < bis' fisis' > 1  |
                < ais' eis' > 1  |
                < bis' fisis' > 2 -\tenuto r4 < e'' ais' >  |
%% 50
                < fis'' cisis'' > 2 -\tenuto r4 < ais' eis' >  |
                < bis' fisis' > 1  |
                < ais' eis' > 1  |
                < bis fisis > 8. r16 r8 < dis' gis > 4 -\tenuto r8 r < e' b > -\tenuto 
                % warning: overlong bar truncated here |
                \skip 8 r8 r4 r2  |
%% 55
                < e' ais > 8. r16 r8 < eis' bis > 4 -\tenuto r8 r < fisis' cis' > -\tenuto 
                % warning: overlong bar truncated here |
                \skip 8 r8 r4 r2  |
                < fis' cisis' > 8. r16 r8 < gis' dis' > 4 -\tenuto r8 r < ais' eis' > -\tenuto 
                % warning: overlong bar truncated here |
                \skip 8 r8 r4 r2  |
                < ais' eis' > 8. r16 r8 < bis' fisis' > 4 -\tenuto r8 r < cisis'' gis' > -\tenuto 
                % warning: overlong bar truncated here |
%% 60
                \skip 8 r8 r4 r2  |
                < a' eis' cis' > 4 -\tenuto r8 < a' eis' cis' > 4 -\tenuto r8 < ais' eis' cis' > 8. r16  |
                < a' eis' cis' > 4 -\tenuto r8 < a' eis' cis' > 4 -\tenuto r8 < ais' eis' cis' > 4  |
                < fisis' dis' ais > 4 -\tenuto r8 < fisis' dis' ais > 4 -\tenuto r8 < fisis' dis' ais > 4  |
                < fisis' dis' ais > 4 -\tenuto r8 < fisis' dis' ais > 4 -\tenuto r8 < fisis' dis' ais > 4  |
%% 65
                < a' eis' cis' > 4 -\tenuto r8 < a' eis' cis' > 4 -\tenuto r8 < ais' eis' cis' > 8. r16  |
                < a' eis' cis' > 4 -\tenuto r8 < a' eis' cis' > 4 -\tenuto r8 < ais' eis' cis' > 4  |
                < fisis' dis' ais > 4 -\tenuto r8 < fisis' dis' ais > 4 -\tenuto r8 < fisis' dis' ais > 4  |
                < fisis' dis' ais > 4 -\tenuto r8 < fisis' dis' ais > 4 -\tenuto r8 < fisis' dis' ais > 4  |
                < a' eis' cis' > 4 -\tenuto r8 < a' eis' cis' > 4 -\tenuto r8 < ais' eis' cis' > 8. r16  |
%% 70
                < a' eis' cis' > 4 -\tenuto r8 < a' eis' cis' > 4 -\tenuto r8 < ais' eis' cis' > 4  |
                < fisis' dis' ais > 4 -\tenuto r8 < fisis' dis' ais > 4 -\tenuto r8 < fisis' dis' ais > 4  |
                < fisis' dis' ais > 4 -\tenuto r8 < fisis' dis' ais > 4 -\tenuto r8 < fisis' dis' ais > 4  |
                < a' eis' cis' > 4 -\tenuto r8 < a' eis' cis' > 4 -\tenuto r8 < ais' eis' cis' > 8. r16  |
                < a' eis' cis' > 4 -\tenuto r8 < a' eis' cis' > 4 -\tenuto r8 < ais' eis' cis' > 4  |
%% 75
                < fisis' dis' ais > 4 -\tenuto r8 < fisis' dis' ais > 4 -\tenuto r8 < fisis' dis' ais > 4  |
                < fisis' dis' ais > 4 -\tenuto r8 < fisis' dis' ais > 4 -\tenuto r8 < fisis' dis' ais > 4  |
                < bis' fisis' > 1  |
                < e'' ais' > 2. r4  |
                < fis'' cisis'' > 2. r4  |
%% 80
                < ais' eis' > 1  |
                < dis'' gis' > 2. r4  |
                < eis'' bis' > 2. r4  |
                < gis'' dis'' > 2. r4  |
                < bis' fisis' > 2. r4  |
%% 85
                < bis' fisis' > 1  |
                < e'' ais' > 2. r4  |
                < fis'' cisis'' > 2. r4  |
                < ais' eis' > 1  |
                < dis'' gis' > 2. r4  |
%% 90
                < eis'' bis' > 2. r4  |
                < gis'' dis'' > 2. r4  |
                < bis' fisis' > 2 -\tenuto r8 r16  |
            } % Voice
        >> % Staff ends

        \context Staff = "track 5, bata" << 
            \set Staff.instrumentName = \markup { \column { "bata " } }
            \set Staff.midiInstrument = ""
            \set Score.skipBars = ##t
            \set Staff.printKeyCancellation = ##f
            \new Voice \global
            \new Voice \globalTempo

            \context Voice = "voice 5" {
                \override Voice.TextScript #'padding = #2.0
                \override MultiMeasureRest #'expand-limit = 1

                
                \clef "bass_15"
                \key dis \minor
                e, 16 r r8 e, 16 r r8 e, 16 r r8 r cis, 16 cis,  |
                < bis,, dis, > 16 r r bis,, dis, r cis, r < bis,, dis, > r r8 < cis, dis, > 16 r e, r  |
                < dis, bis,, > 16 r r bis,, dis, r cis, r < dis, bis,, > r r8 < dis, cis, > 16 r dis, e,  |
%% 5
                < dis, bis,, > 16 r r bis,, dis, r cis, r < dis, bis,, > r r8 < dis, cis, > 16 r e, r  |
                < dis, bis,, > 16 r r bis,, dis, r cis, r < dis, bis,, > r r8 < dis, cis, > 16 r r cis,  |
                < bis,, dis, > 16 r r bis,, dis, r cis, r < bis,, dis, > r r8 < cis, dis, > 16 r e, r  |
                < dis, bis,, > 16 r r bis,, dis, r cis, r < dis, bis,, > r r8 < dis, cis, > 16 r dis, e,  |
                < dis, bis,, > 16 r r bis,, dis, r cis, r < dis, bis,, > r r8 < dis, cis, > 16 r e, r  |
%% 10
                < dis, bis,, > 16 r r bis,, dis, r cis, r < dis, bis,, > r r8 < dis, cis, > 16 r r cis,  |
                < bis,, dis, > 16 r r bis,, dis, r cis, r < bis,, dis, > r r8 < cis, dis, > 16 r e, r  |
                < dis, bis,, > 16 r r bis,, dis, r cis, r < dis, bis,, > r r8 < dis, cis, > 16 r dis, e,  |
                < dis, bis,, > 16 r r bis,, dis, r cis, r < dis, bis,, > r r8 < dis, cis, > 16 r e, r  |
                < dis, bis,, > 16 r r bis,, dis, r cis, r < dis, bis,, > r r8 < dis, cis, > 16 r r cis,  |
%% 15
                < bis,, dis, > 16 r r bis,, dis, r cis, r < bis,, dis, > r r8 < cis, dis, > 16 r e, r  |
                < dis, bis,, > 16 r r bis,, dis, r cis, r < dis, bis,, > r r8 < dis, cis, > 16 r dis, e,  |
                < dis, bis,, > 16 r r bis,, dis, r cis, r < dis, bis,, > r r8 < dis, cis, > 16 r e, r  |
                < dis, bis,, > 16 r r bis,, dis, r cis, r < dis, bis,, > r r8 < dis, cis, > 16 r r cis,  |
                < dis, cis, > 16 r r cis, r8 cis, 16 r cis, r r cis, < cisis, dis, > cisis, < cisis, dis, > cisis,  |
%% 20
                < dis, bis,, > 16 r r bis,, < dis, cis, > r r8 < dis, bis,, > 16 r r bis,, dis, r < e, cis, > r  |
                < bis,, dis, > 16 r r bis,, < cis, dis, > r r8 < bis,, dis, > 16 r r bis,, dis, r < cis, e, > r  |
                < bis,, dis, > 16 r r bis,, < cis, dis, > r r8 < bis,, dis, > 16 r r bis,, dis, r < cis, e, > r  |
                < bis,, dis, > 16 r r bis,, < cis, dis, > r r8 < bis,, dis, > 16 r r bis,, dis, r < cis, e, > r  |
                < bis,, dis, > 16 r r bis,, < cis, dis, > r r8 < bis,, dis, > 16 r r bis,, dis, r < cis, e, > r  |
%% 25
                < bis,, dis, > 16 r r bis,, < cis, dis, > r r8 < bis,, dis, > 16 r r bis,, dis, r < cis, e, > r  |
                < bis,, dis, > 16 r r bis,, < cis, dis, > r r8 < bis,, dis, > 16 r r bis,, dis, r < cis, e, > r  |
                < bis,, dis, > 16 r r bis,, < cis, dis, > r r8 < bis,, dis, > 16 r r bis,, dis, r < cis, e, > r  |
                < dis, bis,, > 16 r r bis,, < dis, cis, > r r8 < dis, bis,, > 16 r r bis,, dis, r < e, cis, > r  |
                < bis,, dis, > 16 r r bis,, < cis, dis, > r r8 < bis,, dis, > 16 r r bis,, dis, r < cis, e, > r  |
%% 30
                < bis,, dis, > 16 r r bis,, < cis, dis, > r r8 < bis,, dis, > 16 r r bis,, dis, r < cis, e, > r  |
                < bis,, dis, > 16 r r bis,, < cis, dis, > r r8 < bis,, dis, > 16 r r bis,, dis, r < cis, e, > r  |
                < bis,, dis, > 16 r r bis,, < cis, dis, > r r8 < bis,, dis, > 16 r r bis,, dis, r < cis, e, > r  |
                < bis,, dis, > 16 r r bis,, < cis, dis, > r r8 < bis,, dis, > 16 r r bis,, dis, r < cis, e, > r  |
                < bis,, dis, > 16 r r bis,, < cis, dis, > r r8 < bis,, dis, > 16 r r bis,, dis, r < cis, e, > r  |
%% 35
                < bis,, dis, > 16 r r bis,, < cis, dis, > r r8 < bis,, dis, > 16 r r bis,, dis, r < cis, e, > r  |
                e, 16 r r8 r4 e, 16 r r8 e, 16 r r8  |
                < dis, bis,, > 16 r r bis,, < dis, cis, > r r8 < dis, bis,, > 16 r r bis,, dis, r < e, cis, > r  |
                < bis,, dis, > 16 r r bis,, < cis, dis, > r r8 < bis,, dis, > 16 r r bis,, dis, r < cis, e, > r  |
                < bis,, dis, > 16 r r bis,, < cis, dis, > r r8 < bis,, dis, > 16 r r bis,, dis, r < cis, e, > r  |
%% 40
                < bis,, dis, > 16 r r bis,, < cis, dis, > r r8 < bis,, dis, > 16 r r bis,, dis, r < cis, e, > r  |
                < dis, bis,, > 16 r r bis,, < dis, cis, > r r8 < dis, bis,, > 16 r r bis,, dis, r < e, cis, > r  |
                < bis,, dis, > 16 r r bis,, < cis, dis, > r r8 < bis,, dis, > 16 r r bis,, dis, r < cis, e, > r  |
                < bis,, dis, > 16 r r bis,, < cis, dis, > r r8 < bis,, dis, > 16 r r bis,, dis, r < cis, e, > r  |
                < bis,, dis, > 16 r r bis,, < cis, dis, > r r8 < bis,, dis, > 16 r r bis,, dis, r < cis, e, > r  |
%% 45
                < dis, bis,, > 16 r r bis,, < dis, cis, > r r8 < dis, bis,, > 16 r r bis,, dis, r < e, cis, > r  |
                < bis,, dis, > 16 r r bis,, < cis, dis, > r r8 < bis,, dis, > 16 r r bis,, dis, r < cis, e, > r  |
                < bis,, dis, > 16 r r bis,, < cis, dis, > r r8 < bis,, dis, > 16 r r bis,, dis, r < cis, e, > r  |
                < bis,, dis, > 16 r r bis,, < cis, dis, > r r8 < bis,, dis, > 16 r r bis,, dis, r < cis, e, > r  |
                < dis, bis,, > 16 r r bis,, < dis, cis, > r r8 < dis, bis,, > 16 r r bis,, dis, r < e, cis, > r  |
%% 50
                < bis,, dis, > 16 r r bis,, < cis, dis, > r r8 < bis,, dis, > 16 r r bis,, dis, r < cis, e, > r  |
                < bis,, dis, > 16 r r bis,, < cis, dis, > r r8 < bis,, dis, > 16 r r bis,, dis, r < cis, e, > r  |
                < bis,, dis, > 16 r r bis,, < cis, dis, > r r8 < bis,, dis, > 16 r r bis,, dis, r < cis, e, > r  |
                < bis,, e, > 16 bis,, r8 dis, 16 r < cis, e, > r < bis,, dis, > r bis,, r dis, r < cis, e, > r  |
                < bis,, dis, > 16 r bis,, r < cis, dis, > r r8 < bis,, dis, > 16 bis,, r bis,, < cis, dis, > r bis,, r  |
%% 55
                < e, bis,, > 16 bis,, r8 dis, 16 r < e, cis, > r < dis, bis,, > r bis,, r dis, r < e, cis, > r  |
                < dis, bis,, > 16 r bis,, r < dis, cis, > r r8 < dis, bis,, > 16 bis,, r bis,, < dis, cis, > r bis,, r  |
                < e, bis,, > 16 bis,, r8 dis, 16 r < e, cis, > r < dis, bis,, > r bis,, r dis, r < e, cis, > r  |
                < dis, bis,, > 16 r bis,, r < dis, cis, > r r8 < dis, bis,, > 16 bis,, r bis,, < dis, cis, > r bis,, r  |
                < e, bis,, > 16 bis,, r8 dis, 16 r < e, cis, > r < dis, bis,, > r bis,, r dis, r < e, cis, > r  |
%% 60
                < dis, bis,, > 16 r bis,, r < dis, cis, > r r8 < dis, bis,, > 16 bis,, r bis,, < dis, cis, > r bis,, r  |
                < bis,, dis, > 16 r r bis,, dis, r cis, r < bis,, dis, > r r8 < cis, dis, > 16 r e, r  |
                < dis, bis,, > 16 r r bis,, dis, r cis, r < dis, bis,, > r r8 < dis, cis, > 16 r dis, e,  |
                < dis, bis,, > 16 r r bis,, dis, r cis, r < dis, bis,, > r r8 < dis, cis, > 16 r e, r  |
                < dis, bis,, > 16 r r bis,, dis, r cis, r < dis, bis,, > r r8 < dis, cis, > 16 r r cis,  |
%% 65
                < bis,, dis, > 16 r r bis,, dis, r cis, r < bis,, dis, > r r8 < cis, dis, > 16 r e, r  |
                < dis, bis,, > 16 r r bis,, dis, r cis, r < dis, bis,, > r r8 < dis, cis, > 16 r dis, e,  |
                < dis, bis,, > 16 r r bis,, dis, r cis, r < dis, bis,, > r r8 < dis, cis, > 16 r e, r  |
                < dis, bis,, > 16 r r bis,, dis, r cis, r < dis, bis,, > r r8 < dis, cis, > 16 r r cis,  |
                < bis,, dis, > 16 r r bis,, dis, r cis, r < bis,, dis, > r r8 < cis, dis, > 16 r e, r  |
%% 70
                < dis, bis,, > 16 r r bis,, dis, r cis, r < dis, bis,, > r r8 < dis, cis, > 16 r dis, e,  |
                < dis, bis,, > 16 r r bis,, dis, r cis, r < dis, bis,, > r r8 < dis, cis, > 16 r e, r  |
                < dis, bis,, > 16 r r bis,, dis, r cis, r < dis, bis,, > r r8 < dis, cis, > 16 r r cis,  |
                < bis,, dis, > 16 r r bis,, dis, r cis, r < bis,, dis, > r r8 < cis, dis, > 16 r e, r  |
                < dis, bis,, > 16 r r bis,, dis, r cis, r < dis, bis,, > r r8 < dis, cis, > 16 r dis, e,  |
%% 75
                < dis, bis,, > 16 r r bis,, dis, r cis, r < dis, bis,, > r r8 < dis, cis, > 16 r e, r  |
                < dis, bis,, > 16 r r bis,, dis, r cis, r < dis, bis,, > r r8 < dis, cis, > 16 r r cis,  |
                < dis, bis,, > 16 r r bis,, < dis, cis, > r r8 < dis, bis,, > 16 r r bis,, dis, r < e, cis, > r  |
                < bis,, dis, > 16 r r bis,, < cis, dis, > r r8 < bis,, dis, > 16 r r bis,, dis, r < cis, e, > r  |
                < bis,, dis, > 16 r r bis,, < cis, dis, > r r8 < bis,, dis, > 16 r r bis,, dis, r < cis, e, > r  |
%% 80
                < bis,, dis, > 16 r r bis,, < cis, dis, > r r8 < bis,, dis, > 16 r r bis,, dis, r < cis, e, > r  |
                < bis,, dis, > 16 r r bis,, < cis, dis, > r r8 < bis,, dis, > 16 r r bis,, dis, r < cis, e, > r  |
                < bis,, dis, > 16 r r bis,, < cis, dis, > r r8 < bis,, dis, > 16 r r bis,, dis, r < cis, e, > r  |
                < bis,, dis, > 16 r r bis,, < cis, dis, > r r8 < bis,, dis, > 16 r r bis,, dis, r < cis, e, > r  |
                < bis,, dis, > 16 r r bis,, < cis, dis, > r r8 < bis,, dis, > 16 r r bis,, dis, r < cis, e, > r  |
%% 85
                < dis, bis,, > 16 r r bis,, < dis, cis, > r r8 < dis, bis,, > 16 r r bis,, dis, r < e, cis, > r  |
                < bis,, dis, > 16 r r bis,, < cis, dis, > r r8 < bis,, dis, > 16 r r bis,, dis, r < cis, e, > r  |
                < bis,, dis, > 16 r r bis,, < cis, dis, > r r8 < bis,, dis, > 16 r r bis,, dis, r < cis, e, > r  |
                < bis,, dis, > 16 r r bis,, < cis, dis, > r r8 < bis,, dis, > 16 r r bis,, dis, r < cis, e, > r  |
                < bis,, dis, > 16 r r bis,, < cis, dis, > r r8 < bis,, dis, > 16 r r bis,, dis, r < cis, e, > r  |
%% 90
                < bis,, dis, > 16 r r bis,, < cis, dis, > r r8 < bis,, dis, > 16 r r bis,, dis, r < cis, e, > r  |
                < bis,, dis, > 16 r r bis,, < cis, dis, > r r8 < bis,, dis, > 16 r r bis,, dis, r < cis, e, > r  |
                < bis,, dis, > 16 r r bis,, < cis, dis, > r r8 < bis,, dis, > 16 r r bis,, dis, r < cis, e, >  |
            } % Voice
        >> % Staff (final) ends

    >> % notes

    \layout {
        \context { \GrandStaff \accepts "Lyrics" }
    }
%     uncomment to enable generating midi file from the lilypond source
%         \midi {
%         } 
} % score
